(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const cfg=window.HP_CONFIG||{};
const ready=!!(window.supabase&&cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY&&!String(cfg.SUPABASE_URL).includes('YOUR_'));
const sb=ready?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY):null;
const LOCAL_CATALOG=__CATALOG__;
const categories=['Tractors','Combine Harvesters','Straw Reapers','Seed Drills','Rotavators','Cultivators','Balers','Sprayers','Irrigation Systems','Smart Farming','Spare Parts','Tyres & Engines','Harvesters','Threshers','Loaders','Trailers'];
const states=['Punjab','Haryana','Uttar Pradesh','Rajasthan','Madhya Pradesh','Maharashtra','Gujarat','Bihar','Delhi','Himachal Pradesh','Uttarakhand','Tamil Nadu','Telangana','Karnataka','Kerala','West Bengal','Odisha','Assam','Andhra Pradesh','Other'];
const brands=['Harvester Parts','Mahindra','Swaraj','Sonalika','John Deere','New Holland','Massey Ferguson','Eicher','Kubota','Preet','Claas','Shaktiman','Fieldking','Dasmesh','Landforce','Other'];
const S={user:null,profile:null,seller:null,products:[...LOCAL_CATALOG],cart:JSON.parse(localStorage.hp_cart||'[]'),filters:{q:'',type:'',category:'',brand:'',state:''},counts:{products:0,sellers:0},unread:0};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const authId=()=>S.user?.id||null;
const isAdmin=()=>String(S.profile?.role||'').toLowerCase()==='admin'||String(S.user?.email||'').toLowerCase()===String(cfg.ADMIN_EMAIL||'kiratveersinghralhan@gmail.com').toLowerCase();
const isSeller=()=>['seller','dealer','admin'].includes(String(S.profile?.role||'').toLowerCase())||['approved','provisional'].includes(String(S.seller?.status||'').toLowerCase());
const img=(p)=>esc(p?.image_url||p?.image_urls?.[0]||'https://placehold.co/900x650/f7f2e8/0f2b1d?text=Harvester+Parts');
function toast(msg){const t=$('#toast'); if(!t){alert(msg);return;} t.textContent=msg; t.classList.add('show'); clearTimeout(t._tm); t._tm=setTimeout(()=>t.classList.remove('show'),3200)}
function loading(on,text='Processing...'){const el=$('#loadingOverlay'); if(!el)return; $('#loadingText').textContent=text; el.classList.toggle('show',!!on); el.setAttribute('aria-hidden',on?'false':'true')}
async function withLoading(text,fn){loading(true,text); try{return await fn()} finally{loading(false)}}
function saveCart(){localStorage.hp_cart=JSON.stringify(S.cart); $('#cartCount')&&($('#cartCount').textContent=S.cart.reduce((a,i)=>a+(i.qty||1),0));}
function hideIntro(){const i=$('#intro'); if(i){i.classList.add('hide'); setTimeout(()=>i.remove(),550)}}
async function init(){setTimeout(hideIntro,700); setTimeout(hideIntro,1800); bindGlobal(); await auth(); await loadProducts(); await loadCounts(); route(); saveCart(); hideIntro(); if('serviceWorker' in navigator){try{const regs=await navigator.serviceWorker.getRegistrations(); for(const r of regs) await r.update().catch(()=>{}); navigator.serviceWorker.register('./sw.js?v=41').catch(()=>{});}catch(e){}}}
function bindGlobal(){window.addEventListener('hashchange',route); $('#menuBtn')?.addEventListener('click',()=>$('#drawer')?.classList.add('open')); $$('[data-close],.drawer-bg').forEach(x=>x.addEventListener('click',()=>$('#drawer')?.classList.remove('open'))); $('#accountBtn')?.addEventListener('click',()=>S.user?location.hash='account':authModal()); $('#cartBubble')?.addEventListener('click',()=>location.hash='cart'); $('#scrollTop')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'})); addEventListener('scroll',()=>$('#scrollTop')?.classList.toggle('show',scrollY>500)); document.body.addEventListener('click',e=>{const r=e.target.closest('[data-route]'); if(r){location.hash=r.dataset.route; $('#drawer')?.classList.remove('open')}})}
async function auth(){ if(!sb)return; const {data}=await sb.auth.getUser(); S.user=data?.user||null; await loadProfile(); await loadSeller(); await loadUnread(); updateAccountUI(); }
async function loadProfile(){ if(!sb||!S.user){S.profile=null;return;} let {data,error}=await sb.from('users').select('*').eq('auth_id',authId()).maybeSingle(); if(!data&&!error){await sb.from('users').insert({auth_id:authId(),email:S.user.email,phone:S.user.phone,role:String(S.user.email).toLowerCase()==='kiratveersinghralhan@gmail.com'?'admin':'user',user_uid:'HP-'+authId().replace(/-/g,'').slice(0,8).toUpperCase()}); ({data}=await sb.from('users').select('*').eq('auth_id',authId()).maybeSingle());} if(data&&String(S.user.email).toLowerCase()==='kiratveersinghralhan@gmail.com'&&data.role!=='admin'){await sb.from('users').update({role:'admin'}).eq('auth_id',authId()); data.role='admin';} S.profile=data||null; }
async function loadSeller(){ if(!sb||!S.user){S.seller=null;return;} const {data}=await sb.from('sellers').select('*').eq('user_id',authId()).maybeSingle(); S.seller=data||null; if(data?.status==='approved'&&!localStorage.getItem('hp_approved_'+authId())){setTimeout(()=>celebration('Seller Verified','Congratulations! Your seller account is now active.'),600); localStorage.setItem('hp_approved_'+authId(),'yes')} }
async function loadProducts(){ S.products=[...LOCAL_CATALOG]; if(!sb)return; try{const {data,error}=await sb.from('products').select('*').in('status',['approved']).order('created_at',{ascending:false}); if(!error&&data)S.products=[...LOCAL_CATALOG,...data];}catch(e){console.warn(e)} }
async function loadCounts(){ S.counts.products=S.products.filter(p=>p.status==='approved').length; S.counts.sellers=1; if(sb){try{let {count:p}=await sb.from('products').select('*',{count:'exact',head:true}).eq('status','approved');let {count:s}=await sb.from('sellers').select('*',{count:'exact',head:true}).eq('status','approved');S.counts.products=(p||0)+LOCAL_CATALOG.length;S.counts.sellers=(s||0)+1;}catch(e){}} }
async function loadUnread(){ S.unread=0; if(sb&&S.user){try{const {count}=await sb.from('notifications').select('*',{count:'exact',head:true}).eq('user_id',authId()).eq('is_read',false); S.unread=count||0;}catch(e){}} const b=$('#notifBadge'); if(b)b.textContent=S.unread?S.unread:''; }
function updateAccountUI(){const btn=$('#accountBtn'); if(btn)btn.textContent=S.user?'Account':'Login'; const box=$('#drawerAccount'); if(!box)return; if(!S.user){box.innerHTML=`<b>Welcome</b><p>Login to buy, sell and manage orders.</p><button class="btn" onclick="window.hpAuth&&window.hpAuth()">Login</button>`;return;} const title=S.profile?.badge_title|| (isSeller()?'Verified Seller':'Member'); box.innerHTML=`<b>${esc(S.profile?.full_name||S.user.email)}</b><p>${esc(S.profile?.user_uid||'HP User')} • ${esc(title)}</p><div style="display:flex;gap:10px;align-items:center"><button class="btn small" data-route="account">My Account</button><button id="logoutMini" class="ghost">Logout</button></div>`; $('#logoutMini')?.addEventListener('click',async()=>{await sb?.auth.signOut(); localStorage.removeItem('hp_approved_'+authId()); S.user=null;S.profile=null;S.seller=null; updateAccountUI(); location.hash='home'; toast('Logged out')});}
function route(){const page=(location.hash||'#home').slice(1).split('/')[0]||'home'; const app=$('#app'); if(!app)return; app.innerHTML=(PAGES[page]||PAGES.home)(); app.querySelectorAll('.reveal').forEach((el,i)=>setTimeout(()=>el.classList.add('in'),60*i)); bindPage(page); updateAccountUI(); saveCart(); scrollTo(0,0)}
const PAGES={home,marketplace,sell,dashboard,account,cart,checkout,orders,messages,notifications,plans,badges,policy,admin,reports,wishlist,ai,product:productPage};
function home(){return `<section class="hero"><div><p class="eyebrow">Verified Agri Marketplace</p><h1>Buy and sell agri machines, spares and factory stock.</h1><p>Harvester Parts connects buyers, farmers, dealers and verified sellers for agricultural machinery and spare parts.</p><div class="hero-actions"><button class="btn" data-route="marketplace">Browse Marketplace</button><button class="btn dark" data-route="sell">Sell Product</button><button class="ghost" data-route="badges">Trust Badges</button></div></div><div class="hero-img"></div></section><div class="stats"><div class="stat"><b>${S.counts.products}</b><span>Products</span></div><div class="stat"><b>${S.counts.sellers}</b><span>Sellers</span></div><div class="stat"><b>32</b><span>States covered</span></div></div><section class="section"><p class="eyebrow">Categories</p><h2>Shop by farming need.</h2><div class="grid">${categories.slice(0,6).map(c=>`<button class="card category" data-cat="${esc(c)}"><b>${esc(c)}</b><span>View listings</span></button>`).join('')}</div></section><section class="section"><p class="eyebrow">Factory Stock</p><h2>Latest spare parts.</h2><div class="products">${S.products.slice(0,6).map(productCard).join('')}</div></section>`}
function marketplace(){const f=S.filters; let list=S.products.filter(p=>!f.q||JSON.stringify(p).toLowerCase().includes(f.q.toLowerCase())).filter(p=>!f.category||p.category===f.category).filter(p=>!f.brand||p.brand===f.brand).filter(p=>!f.state||p.state===f.state).filter(p=>!f.type||p.sale_type===f.type||p.condition===f.type); return `<section class="section"><p class="eyebrow">Marketplace</p><h2>Browse machines and spare parts.</h2></section><div class="filters"><input id="q" placeholder="Search products" value="${esc(f.q)}"><select id="type"><option value="">All types</option><option value="catalog_spare">Spare parts</option><option value="spare_part">Checkout parts</option><option value="machine">Machines</option></select><select id="cat"><option value="">All categories</option>${categories.map(c=>`<option ${f.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select><select id="brand"><option value="">All brands</option>${brands.map(b=>`<option ${f.brand===b?'selected':''}>${esc(b)}</option>`).join('')}</select><select id="state"><option value="">All states</option>${states.map(s=>`<option ${f.state===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div><div class="products">${list.map(productCard).join('')||'<div class="empty">No products found.</div>'}</div>`}
function productCard(p){return `<article class="product"><a href="#product/${esc(p.id)}"><img src="${img(p)}" onerror="this.src='https://placehold.co/900x650/f7f2e8/0f2b1d?text=Harvester+Parts'"><div class="pbody"><div class="tags"><span class="tag">${esc(p.category||'Product')}</span>${p.verified||p.verification_status==='approved'?'<span class="tag">Verified</span>':''}</div><h3>${esc(p.title)}</h3><p>${esc(p.city||'India')} • ${esc(p.condition||'Available')}</p><div class="price">${money(p.price)}</div></div></a><button class="btn small" data-product="${esc(p.id)}">${p.sale_type==='spare_part'?'Add to Cart':'Message Seller'}</button></article>`}
function productPage(){const id=decodeURIComponent((location.hash.split('/')[1]||'')); const p=S.products.find(x=>String(x.id)===String(id)); if(!p)return `<div class="empty">Product not found.</div>`; const similar=S.products.filter(x=>x.id!==p.id&&x.category===p.category).slice(0,3); return `<section class="detail"><div><div class="gallery"><img src="${img(p)}" onerror="this.src='https://placehold.co/900x650/f7f2e8/0f2b1d?text=Harvester+Parts'"></div><section class="section"><h2>${esc(p.title)}</h2><p>${esc(p.description||'Contact seller for full details and compatibility.')}</p><div class="specs">${[['Brand',p.brand],['Model',p.model],['Condition',p.condition],['Weight',p.weight_kg?`${p.weight_kg} kg`:'' ],['Engine No.',p.engine_number],['Chassis No.',p.chassis_number],['Location',[p.city,p.district,p.state].filter(Boolean).join(', ')]].map(a=>`<div class="spec"><b>${a[0]}</b><p>${esc(a[1]||'Not provided')}</p></div>`).join('')}</div></section><section class="section"><h2>Similar products</h2><div class="products">${similar.map(productCard).join('')||'<div class="empty">No similar products yet.</div>'}</div></section></div><aside class="card buybox"><p class="eyebrow">Verified Listing</p><h2>${money(p.price)}</h2><p>${esc(p.seller_name||'Verified seller')}</p><button class="btn" style="width:100%" data-product="${esc(p.id)}">${p.sale_type==='spare_part'?'Add to Cart':'Message Seller'}</button><button class="ghost" id="saveWish" data-wish="${esc(p.id)}" style="width:100%;margin-top:10px">Save to Wishlist</button><button class="ghost" id="reportBtn" style="width:100%;margin-top:10px">Report Listing</button><div id="reviewsBox"></div></aside></section>`}
function sell(){if(!S.user)return loginRequired('Login to become a verified seller.'); const status=S.seller?.status||'not submitted'; return `<section class="section"><p class="eyebrow">Sell</p><h2>Only verified sellers can post products.</h2></section><form id="sellerForm" class="form-card forms"><input name="business_name" placeholder="Business / seller name" value="${esc(S.seller?.business_name||S.profile?.full_name||'')}"><input name="phone" placeholder="Phone" value="${esc(S.seller?.phone||S.profile?.phone||'')}"><input class="full" name="address" placeholder="Full address" value="${esc(S.seller?.address||'')}"><label>Aadhaar front<input name="aadhaar_front" type="file" accept="image/*"></label><label>Aadhaar back<input name="aadhaar_back" type="file" accept="image/*"></label><label>Shop photo<input name="shop_photo" type="file" accept="image/*"></label><button class="btn dark full">Submit Verification</button><p class="full smalltxt">Admin will review documents before approval. Status: ${esc(status)}.</p></form>${isSeller()?productForm():''}`}
function productForm(){return `<section class="section"><h2>Post Product</h2></section><form id="productForm" class="form-card forms"><input name="title" placeholder="Product title"><input name="price" type="number" placeholder="Price"><select name="category">${categories.map(c=>`<option>${esc(c)}</option>`).join('')}</select><select name="brand">${brands.map(b=>`<option>${esc(b)}</option>`).join('')}</select><input name="model" placeholder="Model"><input name="condition" placeholder="Condition"><input name="weight_kg" type="number" placeholder="Weight KG"><input name="city" placeholder="City"><textarea class="full" name="description" placeholder="Description"></textarea><label class="full">Product image<input type="file" name="image" accept="image/*"></label><button class="btn full">Submit Product for Approval</button></form>`}
function dashboard(){if(!S.user)return loginRequired('Login to view dashboard.'); return `<section class="section"><p class="eyebrow">Dashboard</p><h2>Seller dashboard.</h2></section><div class="admin-grid"><div class="admin-card"><b id="dashProducts">0</b><p>Products</p></div><div class="admin-card"><b>${esc(S.seller?.status||'Not verified')}</b><p>Seller Status</p></div></div><div id="myListings" class="products"></div>`}
function account(){if(!S.user)return loginRequired('Login to manage your account.'); return `<section class="section"><p class="eyebrow">Account</p><h2>Profile and seller status.</h2></section><form id="profileForm" class="form-card forms"><div class="avatar">${S.profile?.profile_image?`<img src="${esc(S.profile.profile_image)}">`:(S.profile?.full_name||S.user.email||'U')[0]}</div><label class="full">Profile photo<input name="photo" type="file" accept="image/*"></label><input name="full_name" placeholder="Full name" value="${esc(S.profile?.full_name||'')}"><input name="phone" placeholder="Phone" value="${esc(S.profile?.phone||S.user.phone||'')}"><select name="gender"><option>${esc(S.profile?.gender||'Gender')}</option><option>Male</option><option>Female</option><option>Other</option></select><input readonly value="${esc(S.profile?.user_uid||'HP User')}"><input readonly value="${esc(S.profile?.role||'user')}"><button class="btn dark full">Save Profile</button><button type="button" id="logout" class="ghost full">Logout</button></form>`}
function cart(){let rows=S.cart.map(i=>{let p=S.products.find(x=>String(x.id)===String(i.id)); if(!p)return ''; return `<div class="cart-row"><img src="${img(p)}"><div><b>${esc(p.title)}</b><p>${money(p.price)} × ${i.qty}</p></div><div class="qty"><button class="circle" data-dec="${p.id}">−</button><b>${i.qty}</b><button class="circle" data-inc="${p.id}">+</button><button class="circle" data-remove="${p.id}">×</button></div></div>`}).join(''); return `<section class="section"><p class="eyebrow">Cart</p><h2>Your cart.</h2></section>${rows||'<div class="empty">Cart is empty.</div>'}<button class="btn" data-route="checkout">Checkout</button>`}
function checkout(){let total=S.cart.reduce((a,i)=>{let p=S.products.find(x=>String(x.id)===String(i.id));return a+(p?.price||0)*i.qty},0); return `<section class="checkout"><form id="checkoutForm" class="form-card"><p class="eyebrow">Checkout</p><h2>Place Secure Order</h2><input name="name" placeholder="Full name"><input name="phone" placeholder="Phone"><textarea name="address" placeholder="Delivery address"></textarea><label class="payment-card"><input type="radio" name="method" value="razorpay" checked> Razorpay Online</label><label class="payment-card"><input type="radio" name="method" value="cod"> Pay after seller confirmation</label><button class="btn dark" style="width:100%">Place Secure Order</button></form><aside class="card"><p class="eyebrow">Order Summary</p><h2>${money(total)}</h2><p>${S.cart.length} items</p></aside></section>`}
function orders(){return `<section class="section"><p class="eyebrow">Orders</p><h2>Your orders.</h2></section><div id="ordersList"></div>`}
function messages(){return `<section class="section"><p class="eyebrow">Messages</p><h2>Website messages.</h2></section><div id="messageList"></div><form id="replyForm" class="form-card forms"><input name="receiver" placeholder="Receiver ID"><textarea name="message" placeholder="Message"></textarea><button class="btn full">Send Message</button></form>`}
function notifications(){return `<section class="section"><p class="eyebrow">Notifications</p><h2>Important updates.</h2></section><div id="notificationList"></div>`}
function wishlist(){let ids=JSON.parse(localStorage.hp_wishlist||'[]'); let list=S.products.filter(p=>ids.includes(String(p.id))); return `<section class="section"><p class="eyebrow">Wishlist</p><h2>Saved products.</h2></section><div class="products">${list.map(productCard).join('')||'<div class="empty">No saved products.</div>'}</div>`}
function plans(){let data=[['Starter',999],['Basic',2999],['Growth',4999],['Gold',7999],['Dealer',11999],['Elite',15999]]; return `<section class="section"><p class="eyebrow">Plans</p><h2>Seller plans.</h2></section><div class="grid">${data.map(([n,a])=>`<div class="card"><p class="eyebrow">${n}</p><h2>${money(a)}</h2><p>Boost listings, leads and visibility.</p><button class="btn" data-plan="${a}" data-name="${n}">Buy Plan</button></div>`).join('')}</div>`}
function badges(){let b=['Verified Seller','Trusted Dealer','Top Rated','Fast Responder','100+ Listings','Successful Seller']; return `<section class="section"><p class="eyebrow">Rewards</p><h2>Custom trust badges.</h2><p>Badges appear on seller profile and product pages to build buyer trust.</p></section><div class="grid">${b.map((x,i)=>`<div class="card"><div class="tag">${i?'Locked':'Active'}</div><h3>${esc(x)}</h3><p>${i?'Earn this by activity, ratings or plans.':'Aadhaar/shop verification approved by admin.'}</p></div>`).join('')}</div>`}
function ai(){return `<section class="section"><p class="eyebrow">AI Helper</p><h2>Ask Harvester Parts assistant.</h2></section><div class="form-card"><div id="aiLog"><p><b>AI:</b> Tell me what part, machine, budget or location you need.</p></div><form id="aiForm" class="forms"><input name="q" placeholder="Example: harvester pulley in Ludhiana"><button class="btn">Ask</button></form></div>`}
function reports(){return `<section class="section"><p class="eyebrow">Reports</p><h2>Safety reports.</h2></section><div id="adminReports"></div>`}
function policy(){return `<section class="legal"><p class="eyebrow">Policies</p><h2>Terms, privacy and seller agreement.</h2><p>Harvester Parts is a verified marketplace for agricultural machinery and spare parts. Sellers must provide accurate product details, ownership status, location, price and documents when requested.</p><h3>Seller Agreement</h3><p>Only verified sellers may publish products. Admin approval is required for sellers and listings. Fraudulent, duplicate, misleading or unsafe listings may be removed and accounts may be blocked.</p><h3>Buyer Policy</h3><p>Buyers should inspect machines before final high-value purchase. Spare part orders may use checkout where enabled. Heavy machinery enquiry flow connects buyer and seller.</p><h3>Privacy Policy</h3><p>User profile, verification and order data are stored in Supabase. Verification documents are private and only reviewed for approval.</p></section>`}
function admin(){if(!S.user)return loginRequired('Login as admin.'); if(!isAdmin())return `<section class="section"><p class="eyebrow">Admin</p><h2>Access denied.</h2><p>You are logged in as <b>${esc(S.user.email)}</b>, current role: <b>${esc(S.profile?.role||'unknown')}</b>.</p></section>`; return `<section class="section"><p class="eyebrow">Admin</p><h2>Approvals and marketplace safety.</h2></section><div class="admin-grid"><div class="admin-card"><b>${S.counts.products}</b><p>Approved products</p></div><div class="admin-card"><b>${S.counts.sellers}</b><p>Approved sellers</p></div><div class="admin-card"><b>${S.unread}</b><p>Unread</p></div></div><section class="section"><h2>Pending seller approvals</h2><div id="adminPending" class="grid"></div></section><section class="section"><h2>Reports</h2><div id="adminReports"></div></section>`}
function loginRequired(msg){return `<section class="section"><p class="eyebrow">Login Required</p><h2>${esc(msg)}</h2><button id="openLogin" class="btn">Login / Create Account</button></section>`}
function bindPage(page){ $$('.category').forEach(b=>b.onclick=()=>{S.filters.category=b.dataset.cat;location.hash='marketplace'}); ['q','type','cat','brand','state'].forEach(id=>$('#'+id)?.addEventListener('input',e=>{const map={q:'q',type:'type',cat:'category',brand:'brand',state:'state'};S.filters[map[id]]=e.target.value;route()})); $$('[data-product]').forEach(b=>b.onclick=()=>handleProductAction(b.dataset.product)); $$('[data-route]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.route}); $('#openLogin')?.addEventListener('click',authModal); $('#sellerForm')?.addEventListener('submit',submitSeller); $('#productForm')?.addEventListener('submit',submitProduct); $('#profileForm')?.addEventListener('submit',saveProfile); $('#checkoutForm')?.addEventListener('submit',submitCheckout); $('#replyForm')?.addEventListener('submit',sendManualMessage); $('#logout')?.addEventListener('click',async()=>{await sb?.auth.signOut();S.user=null;S.profile=null;S.seller=null;toast('Logged out');location.hash='home'}); $$('[data-inc]').forEach(b=>b.onclick=()=>{let i=S.cart.find(x=>String(x.id)===String(b.dataset.inc));if(i)i.qty++;saveCart();route()}); $$('[data-dec]').forEach(b=>b.onclick=()=>{let i=S.cart.find(x=>String(x.id)===String(b.dataset.dec));if(i)i.qty--;S.cart=S.cart.filter(x=>x.qty>0);saveCart();route()}); $$('[data-remove]').forEach(b=>b.onclick=()=>{S.cart=S.cart.filter(x=>String(x.id)!==String(b.dataset.remove));saveCart();route()}); $$('[data-plan]').forEach(b=>b.onclick=()=>pay(b.dataset.name,+b.dataset.plan,()=>buyPlan(b.dataset.name,+b.dataset.plan))); $('#saveWish')?.addEventListener('click',saveWishlist); $('#reportBtn')?.addEventListener('click',submitReport); $('#aiForm')?.addEventListener('submit',e=>{e.preventDefault();aiAnswer(new FormData(e.target).get('q'))}); if(page==='admin')loadAdmin(); if(page==='orders')loadOrders(); if(page==='messages')loadMessages(); if(page==='notifications')loadNotifications(); if(page==='dashboard')loadDashboard(); if(page==='reports')loadReports(); if(page==='product')loadReviews(); }
window.hpAuth=authModal;
function authModal(){const m=document.createElement('div');m.className='drawer open';m.innerHTML=`<button class="drawer-bg" data-x></button><section class="drawer-panel"><div class="drawer-head"><h2>Account Access</h2><button class="circle" data-x>×</button></div><div class="tabs"><button type="button" class="tab active" data-mode="login">Login</button><button type="button" class="tab" data-mode="signup">Create Account</button></div><form id="authForm" class="form-card"><input name="name" placeholder="Full name"><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password" required><button id="authSubmit" class="btn dark" style="width:100%">Login</button><p class="smalltxt">Use Create Account if you are new.</p></form></section>`;document.body.appendChild(m);let mode='login';m.querySelectorAll('[data-x]').forEach(x=>x.onclick=()=>m.remove());m.querySelectorAll('[data-mode]').forEach(btn=>btn.onclick=()=>{mode=btn.dataset.mode;m.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===btn));m.querySelector('#authSubmit').textContent=mode==='login'?'Login':'Create Account'});m.querySelector('#authForm').onsubmit=async e=>{e.preventDefault(); if(!sb)return toast('Add Supabase keys first'); await withLoading(mode==='login'?'Logging in...':'Creating account...',async()=>{let fd=new FormData(e.target), email=String(fd.get('email')).trim(), password=String(fd.get('password')); let res=mode==='login'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{data:{full_name:fd.get('name')}}}); if(res.error)toast(res.error.message); else{m.remove();toast(mode==='login'?'Logged in':'Account created'); await auth(); route();}})}}
async function uploadFile(bucket,file,path){if(!file||!sb)return ''; const ext=(file.name.split('.').pop()||'jpg').toLowerCase(); const key=`${path}-${Date.now()}.${ext}`; const {error}=await sb.storage.from(bucket).upload(key,file,{upsert:true,contentType:file.type}); if(error){toast(error.message);return ''} if(bucket==='verification-docs')return key; return sb.storage.from(bucket).getPublicUrl(key).data.publicUrl;}
async function submitSeller(e){e.preventDefault(); if(!sb)return toast('Add Supabase keys first'); if(!S.user)return authModal(); await withLoading('Submitting verification...',async()=>{const fd=new FormData(e.target); const row={user_id:authId(),business_name:String(fd.get('business_name')||'').trim(),phone:String(fd.get('phone')||'').trim(),address:String(fd.get('address')||'').trim(),status:'provisional',verification_status:'pending',ai_review_note:'AI provisional: image files submitted. Admin final approval required.'}; if(!row.business_name||!row.phone)return toast('Please enter name and phone'); for(const k of ['aadhaar_front','aadhaar_back','shop_photo']){const file=fd.get(k); if(file&&file.size){ if(!file.type.startsWith('image/'))return toast('Only image files allowed'); if(file.size>(k==='shop_photo'?5:3)*1024*1024)return toast('File too large. Use smaller image.'); row[k]=await uploadFile('verification-docs',file,`${authId()}/${k}`); if(!row[k])return; }} const {error}=await sb.from('sellers').upsert(row,{onConflict:'user_id'}); if(error)return toast(error.message); await notifyAdmin('Seller verification request',`${row.business_name} submitted verification.`); await loadSeller(); toast('Verification submitted'); route();});}
async function submitProduct(e){e.preventDefault(); if(!sb)return toast('Add Supabase keys first'); if(!S.user)return authModal(); if(!isSeller())return toast('Seller approval required first'); await withLoading('Submitting product...',async()=>{const fd=new FormData(e.target); let image_url=''; const file=fd.get('image'); if(file&&file.size)image_url=await uploadFile('product-images',file,`products/${authId()}`); const row={user_id:authId(),seller_id:S.seller?.id||null,title:fd.get('title'),price:+fd.get('price')||0,category:fd.get('category'),brand:fd.get('brand'),model:fd.get('model'),condition:fd.get('condition'),weight_kg:+fd.get('weight_kg')||0,city:fd.get('city'),description:fd.get('description'),image_url,status:'pending'}; const {error}=await sb.from('products').insert(row); if(error)toast(error.message); else{toast('Product submitted for admin approval'); await notifyAdmin('New product pending',`${row.title} needs approval.`); location.hash='dashboard';}})}
async function saveProfile(e){e.preventDefault(); if(!sb||!S.user)return authModal(); await withLoading('Saving profile...',async()=>{const fd=new FormData(e.target); let profile_image=S.profile?.profile_image; const file=fd.get('photo'); if(file&&file.size)profile_image=await uploadFile('profile-images',file,`profiles/${authId()}`); const payload={full_name:fd.get('full_name'),phone:fd.get('phone'),gender:fd.get('gender'),profile_image,profile_completed:true}; const {error}=await sb.from('users').update(payload).eq('auth_id',authId()); if(error)toast(error.message); else{toast('Profile saved'); await loadProfile(); route();}})}
async function submitCheckout(e){e.preventDefault(); if(!S.user)return authModal(); if(!S.cart.length)return toast('Cart is empty'); const total=S.cart.reduce((a,i)=>{let p=S.products.find(x=>String(x.id)===String(i.id));return a+(p?.price||0)*i.qty},0); const method=new FormData(e.target).get('method'); if(method==='razorpay')pay('Harvester Parts Order',total,res=>createOrder(total,'paid',res)); else createOrder(total,'pending',{});}
async function createOrder(total,status,rzp){if(!sb)return toast('Add Supabase keys first'); const payload={buyer_id:authId(),user_id:authId(),amount:total,status,payment_id:rzp?.razorpay_payment_id||null,razorpay_order_id:rzp?.razorpay_order_id||null}; const {data,error}=await sb.from('orders').insert(payload).select().single(); if(error)return toast(error.message); const items=S.cart.map(i=>{let p=S.products.find(x=>String(x.id)===String(i.id));return{order_id:data.id,product_id:String(i.id).startsWith('factory-')?null:i.id,quantity:i.qty,price:p?.price||0}}); if(items.length)await sb.from('order_items').insert(items); S.cart=[];saveCart();toast('Order placed');location.hash='orders'}
function pay(name,amount,success){if(window.Razorpay&&cfg.RAZORPAY_KEY_ID&&!String(cfg.RAZORPAY_KEY_ID).includes('YOUR_'))new Razorpay({key:cfg.RAZORPAY_KEY_ID,amount:amount*100,currency:'INR',name:'Harvester Parts',description:name,handler:success}).open(); else{toast('Demo payment success');success({})}}
async function buyPlan(name,amount){if(!S.user)return authModal();toast(`${name} plan selected`)}
async function handleProductAction(id){const p=S.products.find(x=>String(x.id)===String(id)); if(!p)return; if(p.sale_type==='spare_part'||p.sale_type==='catalog_spare'){let item=S.cart.find(x=>String(x.id)===String(p.id)); item?item.qty++:S.cart.push({id:p.id,qty:1}); saveCart(); toast('Added to cart'); return;} await createMessage(p,'I am interested in this product. Please share details inside Harvester Parts chat.'); toast('Message sent')}
async function createMessage(p,text){if(!S.user)return authModal(); if(!sb)return; const receiver=p.user_id||p.seller_user_id||null; if(!receiver)return toast('Seller contact available after verified listing'); await sb.from('messages').insert({product_id:String(p.id).startsWith('factory-')?null:p.id,sender_id:authId(),receiver_id:receiver,message:text}); await sb.from('notifications').insert({user_id:receiver,title:'New product enquiry',message:text,type:'message'});}
async function sendManualMessage(e){e.preventDefault(); if(!sb||!S.user)return authModal(); const fd=new FormData(e.target); await sb.from('messages').insert({sender_id:authId(),receiver_id:fd.get('receiver'),message:fd.get('message')}); toast('Message sent')}
function saveWishlist(){const id=String(location.hash.split('/')[1]); let ids=JSON.parse(localStorage.hp_wishlist||'[]'); ids=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]; localStorage.hp_wishlist=JSON.stringify(ids); toast(ids.includes(id)?'Saved':'Removed')}
async function submitReport(){if(!sb||!S.user)return authModal(); const reason=prompt('Why are you reporting this listing?'); if(!reason)return; const id=location.hash.split('/')[1]; await sb.from('reports').insert({target_type:'product',target_id:String(id).startsWith('factory-')?null:id,reporter_id:authId(),reason,status:'open'}); toast('Report submitted')}
async function notifyAdmin(title,message){if(!sb)return; try{const {data}=await sb.from('users').select('auth_id').eq('role','admin'); if(data?.length) await sb.from('notifications').insert(data.map(u=>({user_id:u.auth_id,title,message,type:'admin'})));}catch(e){}}
async function loadAdmin(){if(!sb||!isAdmin())return; const box=$('#adminPending'); if(box){const {data}=await sb.from('sellers').select('*, users(email,full_name,user_uid)').in('status',['pending','provisional']).order('created_at',{ascending:false}); box.innerHTML=(data||[]).map(s=>adminSellerCard(s)).join('')||'<div class="empty">No seller requests.</div>'; $$('[data-doc]').forEach(b=>b.onclick=()=>openDoc(b.dataset.doc)); $$('[data-approve]').forEach(b=>b.onclick=()=>approveSeller(b.dataset.approve)); $$('[data-reject]').forEach(b=>b.onclick=()=>rejectSeller(b.dataset.reject));} loadReports();}
function adminSellerCard(s){return `<div class="card"><p class="eyebrow">${esc(s.status)}</p><h3>${esc(s.business_name||'Seller')}</h3><p><b>Email:</b> ${esc(s.users?.email||'')}</p><p><b>Phone:</b> ${esc(s.phone||'')}</p><p><b>User ID:</b> ${esc(s.users?.user_uid||s.user_id||'')}</p><p><b>Address:</b> ${esc(s.address||'')}</p><p><b>AI:</b> ${esc(s.ai_review_note||'Not checked')}</p>${['aadhaar_front','aadhaar_back','shop_photo'].map(k=>s[k]?`<button class="ghost" data-doc="${esc(s[k])}">${k.replace('_',' ')}</button>`:'').join('')}<div style="margin-top:12px"><button class="btn small" data-approve="${s.id}">Approve</button><button class="ghost" data-reject="${s.id}">Reject</button></div></div>`}
async function openDoc(path){if(!path)return toast('Document not found'); await withLoading('Opening secure document...',async()=>{const {data,error}=await sb.storage.from('verification-docs').createSignedUrl(path,120); if(error||!data?.signedUrl)return toast(error?.message||'Could not open document'); showDocModal(data.signedUrl);});}
function showDocModal(url){const m=document.createElement('div');m.className='drawer open';m.innerHTML=`<button class="drawer-bg" data-x></button><section class="drawer-panel"><div class="drawer-head"><h2>Verification Document</h2><button class="circle" data-x>×</button></div><img src="${esc(url)}" style="width:100%;border-radius:22px;border:1px solid var(--line)" onerror="this.style.display='none';this.nextElementSibling.style.display='block'"><div style="display:none" class="empty">Preview failed. Use open button below.</div><a class="btn" href="${esc(url)}" target="_blank" rel="noopener" style="display:block;text-align:center;margin-top:12px">Open in new tab</a></section>`;document.body.appendChild(m);m.querySelectorAll('[data-x]').forEach(x=>x.onclick=()=>m.remove())}
async function approveSeller(id){await withLoading('Approving seller...',async()=>{const {data,error}=await sb.from('sellers').update({status:'approved',verification_status:'approved',approved_at:new Date().toISOString(),reviewed_by:authId()}).eq('id',id).select().single(); if(error)return toast(error.message); await sb.from('users').update({role:'seller',badge_title:'Verified Seller',badge_color:'green'}).eq('auth_id',data.user_id); await sb.from('notifications').insert({user_id:data.user_id,title:'Seller Approved',message:'Congratulations! Your Harvester Parts seller account is now verified.',type:'approval'}); celebration('Seller Approved','This seller can now post products.'); await loadAdmin();})}
async function rejectSeller(id){const reason=prompt('Rejection reason')||'Rejected by admin'; const {error}=await sb.from('sellers').update({status:'rejected',verification_status:'rejected',rejection_reason:reason}).eq('id',id); if(error)toast(error.message); else{toast('Seller rejected');loadAdmin()}}
async function loadOrders(){if(!sb||!S.user)return; const {data}=await sb.from('orders').select('*').eq('buyer_id',authId()).order('created_at',{ascending:false}); $('#ordersList').innerHTML=(data||[]).map(o=>`<div class="card"><b>${esc(String(o.id).slice(0,8))}</b><p>${money(o.amount)} • ${esc(o.status)}</p><p>${new Date(o.created_at).toLocaleString()}</p></div>`).join('')||'<div class="empty">No orders yet.</div>'}
async function loadMessages(){if(!sb||!S.user)return; const {data}=await sb.from('messages').select('*').or(`sender_id.eq.${authId()},receiver_id.eq.${authId()}`).order('created_at',{ascending:false}); $('#messageList').innerHTML=(data||[]).map(m=>`<div class="card"><b>Message</b><p>${esc(m.message)}</p><small>${new Date(m.created_at).toLocaleString()}</small></div>`).join('')||'<div class="empty">No messages yet.</div>'}
async function loadNotifications(){if(!sb||!S.user)return; const {data}=await sb.from('notifications').select('*').eq('user_id',authId()).order('created_at',{ascending:false}); $('#notificationList').innerHTML=(data||[]).map(n=>`<div class="card"><b>${esc(n.title)}</b><p>${esc(n.message||'')}</p></div>`).join('')||'<div class="empty">No notifications yet.</div>'; const a=(data||[]).find(n=>!n.is_read&&(n.type==='approval'||String(n.title).toLowerCase().includes('approved'))); if(a)celebration(a.title,a.message); await sb.from('notifications').update({is_read:true}).eq('user_id',authId()); loadUnread();}
async function loadDashboard(){if(!sb||!S.user)return; const {data}=await sb.from('products').select('*').eq('user_id',authId()).order('created_at',{ascending:false}); $('#dashProducts')&&($('#dashProducts').textContent=(data||[]).length); $('#myListings')&&($('#myListings').innerHTML=(data||[]).map(productCard).join('')||'<div class="empty">No listings yet.</div>')}
async function loadReports(){const el=$('#adminReports'); if(!el||!sb)return; const q=isAdmin()?sb.from('reports').select('*').order('created_at',{ascending:false}):sb.from('reports').select('*').eq('reporter_id',authId()); const {data}=await q; el.innerHTML=(data||[]).map(r=>`<div class="card"><b>${esc(r.reason)}</b><p>${esc(r.status)}</p></div>`).join('')||'<div class="empty">No open reports.</div>'}
async function loadReviews(){const box=$('#reviewsBox'); if(box)box.innerHTML='<div class="smalltxt">Reviews coming soon.</div>'}
function aiAnswer(q){const log=$('#aiLog'); if(!log)return; const found=S.products.filter(p=>JSON.stringify(p).toLowerCase().includes(String(q).toLowerCase())).slice(0,3); log.innerHTML+=`<p><b>You:</b> ${esc(q)}</p><p><b>AI:</b> ${found.length?'I found matching products: '+found.map(p=>p.title).join(', '):'Tell me category, brand, budget and location for better suggestions.'}</p>`}
function celebration(title,msg){const m=document.createElement('div');m.className='celebration';m.innerHTML=`<button class="circle celeb-close">×</button><div class="confetti left"></div><div class="confetti right"></div><div class="celeb-card"><p class="eyebrow">Success</p><h2>${esc(title||'Approved')}</h2><p>${esc(msg||'Your account is verified.')}</p></div>`;document.body.appendChild(m);m.querySelector('.celeb-close').onclick=()=>m.remove();setTimeout(()=>m.remove(),9000)}
window.addEventListener('DOMContentLoaded',init);
})();
