window.HP_DATA = (() => {
  const categories = [
    ['prime','Power & Prime Movers'],['land','Land Development'],['tillage','Tillage & Soil'],['sowing','Planting & Sowing'],['water','Irrigation & Water'],['nutrient','Fertilizer & Nutrient'],['protection','Crop Protection'],['care','Crop Care'],['harvest','Harvesting'],['post','Post Harvest'],['transport','Transport'],['forage','Hay & Forage'],['livestock','Livestock Field'],['orchard','Orchard'],['smart','Smart Agriculture'],['parts','Spare Parts']
  ];
  const brands = ['Mahindra','Swaraj','Sonalika','John Deere','New Holland','Massey Ferguson','Kubota','CLAAS','Yanmar','Case IH','TAFE','Eicher','Escorts','Preet','Shaktiman','Fieldking','Lemken','Dasmesh','Landforce','Kartar'];
  const states = ['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal','Andaman and Nicobar Islands','Chandigarh','Dadra and Nagar Haveli and Daman and Diu','Delhi','Jammu and Kashmir','Ladakh','Lakshadweep','Puducherry','Worldwide'];
  const districtsByState = {
    'Punjab':['Amritsar','Barnala','Bathinda','Faridkot','Fatehgarh Sahib','Fazilka','Ferozepur','Gurdaspur','Hoshiarpur','Jalandhar','Kapurthala','Ludhiana','Malerkotla','Mansa','Moga','Mohali','Muktsar','Pathankot','Patiala','Rupnagar','Sangrur','Shaheed Bhagat Singh Nagar','Tarn Taran'],
    'Haryana':['Ambala','Bhiwani','Charkhi Dadri','Faridabad','Fatehabad','Gurugram','Hisar','Jhajjar','Jind','Kaithal','Karnal','Kurukshetra','Mahendragarh','Nuh','Palwal','Panchkula','Panipat','Rewari','Rohtak','Sirsa','Sonipat','Yamunanagar'],
    'Uttar Pradesh':['Agra','Aligarh','Ayodhya','Azamgarh','Bareilly','Basti','Bijnor','Bulandshahr','Etawah','Gautam Buddha Nagar','Ghaziabad','Gorakhpur','Jaunpur','Jhansi','Kanpur Nagar','Lakhimpur Kheri','Lucknow','Meerut','Moradabad','Muzaffarnagar','Prayagraj','Saharanpur','Sitapur','Varanasi'],
    'Rajasthan':['Ajmer','Alwar','Banswara','Barmer','Bharatpur','Bhilwara','Bikaner','Chittorgarh','Churu','Dausa','Ganganagar','Hanumangarh','Jaipur','Jaisalmer','Jodhpur','Kota','Nagaur','Pali','Sikar','Udaipur'],
    'Madhya Pradesh':['Bhopal','Chhindwara','Dewas','Gwalior','Hoshangabad','Indore','Jabalpur','Mandsaur','Morena','Neemuch','Ratlam','Rewa','Sagar','Satna','Sehore','Ujjain','Vidisha'],
    'Maharashtra':['Ahmednagar','Akola','Amravati','Aurangabad','Beed','Buldhana','Jalgaon','Kolhapur','Latur','Nagpur','Nanded','Nashik','Pune','Sangli','Satara','Solapur','Wardha','Yavatmal'],
    'Gujarat':['Ahmedabad','Amreli','Anand','Banaskantha','Bharuch','Bhavnagar','Gandhinagar','Jamnagar','Junagadh','Kheda','Kutch','Mehsana','Rajkot','Sabarkantha','Surat','Vadodara','Valsad'],
    'Bihar':['Araria','Begusarai','Bhagalpur','Bhojpur','Darbhanga','Gaya','Katihar','Madhubani','Muzaffarpur','Nalanda','Patna','Purnia','Samastipur','Saran','Siwan','Vaishali'],
    'Tamil Nadu':['Ariyalur','Chennai','Coimbatore','Cuddalore','Dharmapuri','Dindigul','Erode','Madurai','Namakkal','Salem','Thanjavur','Tiruchirappalli','Tirunelveli','Tiruppur','Vellore','Villupuram'],
    'Telangana':['Adilabad','Hyderabad','Jagtial','Karimnagar','Khammam','Mahabubnagar','Medak','Nalgonda','Nizamabad','Rangareddy','Sangareddy','Siddipet','Warangal'],
    'Karnataka':['Bagalkot','Ballari','Belagavi','Bengaluru Rural','Bengaluru Urban','Bidar','Chikkaballapur','Dharwad','Hassan','Haveri','Kalaburagi','Mandya','Mysuru','Raichur','Shivamogga','Tumakuru','Vijayapura'],
    'Andhra Pradesh':['Anantapur','Chittoor','East Godavari','Guntur','Kadapa','Krishna','Kurnool','Nellore','Prakasam','Srikakulam','Visakhapatnam','Vizianagaram','West Godavari'],
    'West Bengal':['Bankura','Birbhum','Hooghly','Howrah','Jalpaiguri','Malda','Murshidabad','Nadia','North 24 Parganas','Paschim Bardhaman','Purba Bardhaman','Purba Medinipur','South 24 Parganas'],
    'Kerala':['Alappuzha','Ernakulam','Idukki','Kannur','Kasaragod','Kollam','Kottayam','Kozhikode','Malappuram','Palakkad','Pathanamthitta','Thrissur','Wayanad'],
    'Odisha':['Angul','Balangir','Balasore','Bargarh','Bhadrak','Cuttack','Ganjam','Jajpur','Kalahandi','Keonjhar','Koraput','Mayurbhanj','Puri','Sambalpur','Sundargarh'],
    'Assam':['Barpeta','Darrang','Dibrugarh','Goalpara','Golaghat','Jorhat','Kamrup','Karimganj','Lakhimpur','Nagaon','Sivasagar','Sonitpur','Tinsukia'],
    'Chhattisgarh':['Balod','Bilaspur','Durg','Janjgir-Champa','Korba','Raipur','Rajnandgaon'],
    'Jharkhand':['Bokaro','Deoghar','Dhanbad','East Singhbhum','Giridih','Hazaribagh','Ranchi','West Singhbhum'],
    'Delhi':['Central Delhi','East Delhi','New Delhi','North Delhi','South Delhi','West Delhi'],
    'Chandigarh':['Chandigarh'],'Goa':['North Goa','South Goa'],'Himachal Pradesh':['Bilaspur','Hamirpur','Kangra','Kullu','Mandi','Shimla','Solan','Una'],'Uttarakhand':['Almora','Dehradun','Haridwar','Nainital','Pauri Garhwal','Udham Singh Nagar','Uttarkashi'],'Jammu and Kashmir':['Anantnag','Baramulla','Budgam','Jammu','Kathua','Pulwama','Rajouri','Samba','Srinagar','Udhampur'],'Worldwide':['Global']
  };
  const languages = ['English','हिन्दी','ਪੰਜਾਬੀ','தமிழ்','తెలుగు','ಕನ್ನಡ','বাংলা','ગુજરાતી','मराठी','اردو','മലയാളം','ଓଡ଼ିଆ','অসমীয়া','नेपाली','العربية','Français','Español'];
  const plans = [{name:'Starter',price:999,listings:5,boosts:0,tag:'First seller'},{name:'Kisan Plus',price:2999,listings:20,boosts:2,tag:'Farmers'},{name:'Trader',price:4999,listings:50,boosts:5,tag:'Active sellers'},{name:'Dealer Gold',price:7999,listings:120,boosts:12,tag:'Best value'},{name:'Royal Dealer',price:11999,listings:250,boosts:25,tag:'Showroom'},{name:'Enterprise',price:15999,listings:999,boosts:60,tag:'Multi-city'}];
  const titles = ['Verified Farmer','Rising Seller','Top Dealer','Harvest Pro','Parts Specialist','Royal Trader'];
  const catalogNames = ['John Deere 5310 4WD Tractor','Mahindra Arjun Novo 605','Swaraj 744 FE Refined','New Holland Combine TC5.30','CLAAS Crop Tiger Harvester','Preet 987 Combine Harvester','Shaktiman Rotavator 7ft','Fieldking Disc Harrow','Laser Land Leveler Kit','Sonalika Sikander Tractor','Massey Ferguson 241 DI','Kubota MU5502 4WD','Seed Drill 13 Row','Happy Seeder Super SMS','Straw Reaper Heavy Duty','Baler Square Heavy Duty','Power Weeder Petrol','Boom Sprayer 600L','Drone Sprayer Agri Pro','Diesel Pump Set 10HP','Solar Pump Controller','Tractor Tyre 16.9-28','Hydraulic Pump Assembly','Clutch Plate Kit','Combine Cutter Bar','Harvester Chain Set','Gear Box Assembly','Rice Transplanter','Sugarcane Harvester','Potato Digger','Cotton Picker Attachment','Corn Sheller','Grain Dryer Mini','Front End Loader','Farm Trailer 12 Ton','Silage Cutter','Mixer Wagon','Orchard Sprayer','GPS Guidance Kit','Autonomous Mini Tractor'];
  const imageQueries = ['tractor farm','combine harvester machine','agricultural machinery','tractor implement','farm tractor india','crop harvester','tractor spare parts','irrigation pump agriculture','seed drill machine','agriculture sprayer drone'];
  const products = Array.from({length:84}, (_,i)=>{
    const isPart = i%5===0 || i%7===0;
    const condition = i%3===0?'Used':'New';
    const category = categories[i%categories.length];
    const brand = brands[i%brands.length];
    const price = isPart ? (3500 + i*850) : (175000 + i*63500);
    const st = states[i%states.length];
    const ds = districtsByState[st] || ['Central'];
    return { id:`P${1000+i}`, name:catalogNames[i%catalogNames.length], category:category[1], categoryId:category[0], brand, model:`${brand.split(' ')[0]}-${(240+i*7)}`, condition:isPart?'Spare Part':condition, type:isPart?'part':'machine', price, oldPrice: Math.round(price*1.12), state:st, district:ds[i%ds.length], village:['Mandi Road','Kisan Nagar','Green Field','Main Bazaar','Agro Estate'][i%5], rating:(4+(i%10)/10).toFixed(1), seller:['Royal Agro Traders','Punjab Kisan Mart','GreenLine Dealers','Bharat Harvest Hub','Mandi Machine Co.'][i%5], verified:true, stock:isPart ? 10+i : 1+(i%4), image:`https://loremflickr.com/1200/850/${encodeURIComponent(imageQueries[i%imageQueries.length]).replace(/%20/g,',')}?lock=${200+i}`, image2:`https://loremflickr.com/900/650/farm,machinery?lock=${500+i}`, image3:`https://loremflickr.com/900/650/tractor,agriculture?lock=${800+i}`, year:2016+(i%9), hours:420+i*67, engineNo:`ENG-${brand.substring(0,3).toUpperCase()}-${82000+i*37}`, chassisNo:`CHS-${100000+i*91}`, ownership:`${1+(i%3)} Owner`, fuel:i%4===0?'Diesel / Electric':'Diesel', hp:isPart?null:35+(i%9)*8, transmission:i%2?'Synchro Shuttle':'Constant Mesh', warranty:isPart?'7 day replacement demo':'Inspection assisted sale', saleType:isPart?'Cart Checkout':'Enquiry + Direct Deal', reviews:[{name:'Amanpreet S.',text:'Good seller response and inspection details were clear.'},{name:'Ravi Kumar',text:'Photos and documents matched the listing.'},{name:'Dealer Check',text:'Demo review for layout testing only.'}], desc:'Verified demo listing with inspection-ready details, local enquiry support, finance-ready documents and dealer/farmer contact flow.' }
  });
  return {categories,brands,states,districtsByState,languages,plans,titles,products};
})();
