alter table public.users add column if not exists avatar_url text;
alter table public.users add column if not exists headline text;
alter table public.users add column if not exists bio text;
alter table public.users add column if not exists city text;
alter table public.users add column if not exists state text;
alter table public.users add column if not exists business_type text;
alter table public.users add column if not exists experience_years integer;
alter table public.users add column if not exists profile_completed boolean not null default false;
alter table public.users add column if not exists updated_at timestamptz not null default now();

create or replace view public.public_seller_profiles as
select
  auth_id,
  full_name,
  avatar_url,
  headline,
  bio,
  city,
  state,
  business_type,
  experience_years,
  badge_title,
  rank_title,
  role,
  points,
  profile_completed,
  created_at
from public.users;

grant select on public.public_seller_profiles to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'profile-avatars',
  'profile-avatars',
  true,
  6291456,
  array['image/jpeg','image/png','image/webp','image/avif','image/heic','image/heif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "profile avatars public read" on storage.objects;
create policy "profile avatars public read"
on storage.objects for select
to public
using (bucket_id = 'profile-avatars');

drop policy if exists "users upload own profile avatar" on storage.objects;
create policy "users upload own profile avatar"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'profile-avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "users update own profile avatar" on storage.objects;
create policy "users update own profile avatar"
on storage.objects for update
to authenticated
using (
  bucket_id = 'profile-avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'profile-avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "users delete own profile avatar" on storage.objects;
create policy "users delete own profile avatar"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'profile-avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create table if not exists public.seller_reviews (
  id bigint generated by default as identity primary key,
  seller_id uuid not null,
  reviewer_id uuid not null,
  rating integer not null check (rating between 1 and 5),
  comment text not null default '',
  status text not null default 'approved' check (status in ('approved','hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (seller_id, reviewer_id),
  check (seller_id <> reviewer_id)
);

create index if not exists seller_reviews_seller_created_idx
  on public.seller_reviews (seller_id, created_at desc);

alter table public.seller_reviews enable row level security;

drop policy if exists "public reads approved seller reviews" on public.seller_reviews;
create policy "public reads approved seller reviews"
on public.seller_reviews for select
to anon, authenticated
using (
  status = 'approved'
  or reviewer_id = auth.uid()
  or exists (
    select 1 from public.users u
    where u.auth_id = auth.uid()
      and (u.role = 'admin' or lower(coalesce(u.email,'')) = lower('kiratveersinghralhan@gmail.com'))
  )
);

drop policy if exists "users create own seller review" on public.seller_reviews;
create policy "users create own seller review"
on public.seller_reviews for insert
to authenticated
with check (reviewer_id = auth.uid() and seller_id <> auth.uid());

drop policy if exists "users update own seller review" on public.seller_reviews;
create policy "users update own seller review"
on public.seller_reviews for update
to authenticated
using (
  reviewer_id = auth.uid()
  or exists (
    select 1 from public.users u
    where u.auth_id = auth.uid()
      and (u.role = 'admin' or lower(coalesce(u.email,'')) = lower('kiratveersinghralhan@gmail.com'))
  )
)
with check (
  reviewer_id = auth.uid()
  or exists (
    select 1 from public.users u
    where u.auth_id = auth.uid()
      and (u.role = 'admin' or lower(coalesce(u.email,'')) = lower('kiratveersinghralhan@gmail.com'))
  )
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'users'
  ) then
    alter publication supabase_realtime add table public.users;
  end if;
exception when undefined_object then
  null;
end $$;
