-- Harvester Parts - complete Supabase database setup
-- Version: v114 / 20 June 2026
--
-- Safe to run more than once. This script does not drop tables or delete data.
-- Run the complete file in Supabase Dashboard > SQL Editor.
-- The final query returns an OK/MISSING health report.
--
-- SQL cannot create or configure external services. After this script, separately
-- configure Auth providers, SMTP/SMS, Razorpay keys and the admin-alert Edge Function.

create extension if not exists pgcrypto with schema extensions;

-- -----------------------------------------------------------------------------
-- 1. Core user, seller and marketplace tables
-- -----------------------------------------------------------------------------

create table if not exists public.users (
  auth_id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  phone text not null default '',
  full_name text not null default '',
  gender text not null default '',
  role text not null default 'user',
  user_uid text unique,
  avatar_url text,
  headline text,
  bio text,
  city text,
  state text,
  business_type text,
  experience_years integer not null default 0,
  profile_completed boolean not null default false,
  active_membership text,
  membership_key text,
  membership_title text,
  membership_badge text,
  membership_banner text,
  membership_expires_at timestamptz,
  badge_key text not null default 'buyer_member',
  badge_title text not null default 'Member',
  badge_color text not null default 'green',
  banner_key text,
  banner_title text,
  rank_key text not null default 'starter',
  rank_title text not null default 'Farm Starter',
  title_prefix text,
  points bigint not null default 0,
  is_founder boolean not null default false,
  founder_number integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sellers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.users(auth_id) on delete cascade,
  business_name text not null default '',
  phone text not null default '',
  state text not null default '',
  district text not null default '',
  city text not null default '',
  pincode text not null default '',
  address text not null default '',
  aadhaar_front text,
  aadhaar_back text,
  shop_photo text,
  status text not null default 'pending',
  verification_status text not null default 'pending',
  approved_at timestamptz,
  banned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(auth_id) on delete cascade,
  seller_id uuid references public.sellers(id) on delete set null,
  sell_type text not null default 'spare',
  condition text not null default 'Used',
  title text not null,
  price numeric(14,2) not null default 0,
  category text not null default 'Other',
  brand text,
  model text,
  weight_kg numeric(12,3) not null default 0,
  state text,
  district text,
  city text,
  pincode text,
  description text not null default '',
  image_urls text[] not null default '{}'::text[],
  status text not null default 'approved',
  is_boosted boolean not null default false,
  views bigint not null default 0,
  seller_name text,
  seller_avatar_url text,
  seller_headline text,
  seller_city text,
  seller_state text,
  approved_at timestamptz,
  banned_at timestamptz,
  removed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references public.users(auth_id) on delete restrict,
  user_id uuid references public.users(auth_id) on delete restrict,
  amount numeric(14,2) not null default 0,
  shipping_amount numeric(14,2) not null default 0,
  platform_fee numeric(14,2) not null default 0,
  status text not null default 'pending',
  payment_id text,
  buyer_name text not null default '',
  buyer_phone text not null default '',
  address text not null default '',
  pincode text not null default '',
  shipping_method text,
  coupon_code text,
  coupon_discount numeric(14,2) not null default 0,
  seller_payout_total numeric(14,2) not null default 0,
  platform_commission_total numeric(14,2) not null default 0,
  payout_status text not null default 'pending',
  expected_payout_at timestamptz,
  item_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  quantity numeric(12,3) not null default 1,
  price numeric(14,2) not null default 0,
  seller_user_id uuid references public.users(auth_id) on delete set null,
  platform_commission numeric(14,2) not null default 0,
  seller_amount numeric(14,2) not null default 0,
  payout_status text not null default 'pending_clearance',
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null references public.users(auth_id) on delete cascade,
  receiver_id uuid not null references public.users(auth_id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references public.users(auth_id) on delete cascade,
  reporter_email text,
  target_type text not null default 'product',
  target_id text not null,
  product_id uuid references public.products(id) on delete set null,
  product_title text,
  seller_id uuid references public.users(auth_id) on delete set null,
  reason text not null,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references public.users(auth_id) on delete set null,
  name text not null,
  phone text,
  topic text not null default 'Other',
  message text not null,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- 2. Memberships, rewards, payouts and platform operations
-- -----------------------------------------------------------------------------

create table if not exists public.seller_plans (
  id uuid primary key default gen_random_uuid(),
  plan_key text not null unique,
  name text not null,
  price numeric(12,2) not null default 0,
  duration_days integer not null default 30,
  listing_limit integer not null default 10,
  boost_days integer not null default 0,
  badge text,
  title text,
  banner text,
  reward_points integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.membership_purchases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(auth_id) on delete cascade,
  plan_key text not null,
  plan_name text not null,
  amount numeric(12,2) not null default 0,
  status text not null default 'pending',
  payment_id text,
  starts_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.boost_purchases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(auth_id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  amount numeric(12,2) not null default 0,
  boost_days integer not null default 0,
  status text not null default 'pending',
  payment_id text,
  starts_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.badge_definitions (
  badge_key text primary key,
  name text not null,
  title text,
  tier text,
  description text,
  rarity text,
  sort_order integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.platform_events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  status text not null default 'draft',
  starts_at timestamptz,
  ends_at timestamptz,
  reward_badge_key text references public.badge_definitions(badge_key) on delete set null,
  reward_points integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_payout_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.users(auth_id) on delete cascade,
  payout_method text not null default 'upi',
  upi_id text,
  account_holder_name text,
  bank_name text,
  account_number text,
  ifsc text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_balances (
  user_id uuid primary key references public.users(auth_id) on delete cascade,
  available_balance numeric(14,2) not null default 0,
  pending_balance numeric(14,2) not null default 0,
  paid_balance numeric(14,2) not null default 0,
  platform_fee_total numeric(14,2) not null default 0,
  last_order_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_payout_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(auth_id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  status text not null default 'requested',
  payout_method text not null default 'upi',
  upi_id text,
  account_holder_name text,
  bank_name text,
  account_number text,
  ifsc text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seller_ledger (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.users(auth_id) on delete cascade,
  order_id uuid references public.orders(id) on delete set null,
  product_id uuid references public.products(id) on delete set null,
  gross_amount numeric(14,2) not null default 0,
  platform_fee numeric(14,2) not null default 0,
  seller_amount numeric(14,2) not null default 0,
  status text not null default 'pending_clearance',
  available_on date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- 3. Public content, notifications, reviews and analytics
-- -----------------------------------------------------------------------------

create table if not exists public.site_carousel_slides (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  subtitle text,
  image_url text,
  cta_text text not null default 'Open',
  cta_route text not null default 'market',
  sort_order integer not null default 10,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_notifications (
  id uuid primary key default gen_random_uuid(),
  type text not null,
  subject text not null,
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'unread',
  priority text not null default 'important',
  important boolean not null default true,
  admin_email text,
  email_to text,
  email_sent boolean not null default false,
  source text not null default 'harvester-parts-website',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_analytics (
  id bigint generated by default as identity primary key,
  event_type text not null default 'page_view',
  route text not null default 'home',
  product_id text,
  user_id uuid,
  session_id text not null,
  lang text default 'en',
  device text default 'desktop',
  referrer text default 'direct',
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.seller_reviews (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.users(auth_id) on delete cascade,
  reviewer_id uuid not null references public.users(auth_id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  comment text not null default '',
  status text not null default 'approved',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint seller_reviews_not_self check (seller_id <> reviewer_id),
  constraint seller_reviews_seller_reviewer_key unique (seller_id, reviewer_id)
);

-- -----------------------------------------------------------------------------
-- 4. Repair columns in older installations without deleting existing rows
-- -----------------------------------------------------------------------------

do $$
declare
  r record;
begin
  for r in
    select * from (values
      ('users','auth_id','uuid'),
      ('users','email','text not null default '''''),
      ('users','phone','text not null default '''''),
      ('users','full_name','text not null default '''''),
      ('users','gender','text not null default '''''),
      ('users','role','text not null default ''user'''),
      ('users','user_uid','text'),
      ('users','avatar_url','text'),
      ('users','headline','text'),
      ('users','bio','text'),
      ('users','city','text'),
      ('users','state','text'),
      ('users','business_type','text'),
      ('users','experience_years','integer not null default 0'),
      ('users','profile_completed','boolean not null default false'),
      ('users','active_membership','text'),
      ('users','membership_key','text'),
      ('users','membership_title','text'),
      ('users','membership_badge','text'),
      ('users','membership_banner','text'),
      ('users','membership_expires_at','timestamptz'),
      ('users','badge_key','text not null default ''buyer_member'''),
      ('users','badge_title','text not null default ''Member'''),
      ('users','badge_color','text not null default ''green'''),
      ('users','banner_key','text'),
      ('users','banner_title','text'),
      ('users','rank_key','text not null default ''starter'''),
      ('users','rank_title','text not null default ''Farm Starter'''),
      ('users','title_prefix','text'),
      ('users','points','bigint not null default 0'),
      ('users','is_founder','boolean not null default false'),
      ('users','founder_number','integer'),
      ('users','created_at','timestamptz not null default now()'),
      ('users','updated_at','timestamptz not null default now()'),
      ('sellers','user_id','uuid'),
      ('sellers','business_name','text not null default '''''),
      ('sellers','phone','text not null default '''''),
      ('sellers','state','text not null default '''''),
      ('sellers','district','text not null default '''''),
      ('sellers','city','text not null default '''''),
      ('sellers','pincode','text not null default '''''),
      ('sellers','address','text not null default '''''),
      ('sellers','aadhaar_front','text'),
      ('sellers','aadhaar_back','text'),
      ('sellers','shop_photo','text'),
      ('sellers','status','text not null default ''pending'''),
      ('sellers','verification_status','text not null default ''pending'''),
      ('sellers','approved_at','timestamptz'),
      ('sellers','banned_at','timestamptz'),
      ('sellers','created_at','timestamptz not null default now()'),
      ('sellers','updated_at','timestamptz not null default now()'),
      ('products','user_id','uuid'),
      ('products','seller_id','uuid'),
      ('products','sell_type','text not null default ''spare'''),
      ('products','condition','text not null default ''Used'''),
      ('products','title','text'),
      ('products','price','numeric(14,2) not null default 0'),
      ('products','category','text not null default ''Other'''),
      ('products','brand','text'),
      ('products','model','text'),
      ('products','weight_kg','numeric(12,3) not null default 0'),
      ('products','state','text'),
      ('products','district','text'),
      ('products','city','text'),
      ('products','pincode','text'),
      ('products','description','text not null default '''''),
      ('products','image_urls','text[] not null default ''{}''::text[]'),
      ('products','status','text not null default ''approved'''),
      ('products','is_boosted','boolean not null default false'),
      ('products','views','bigint not null default 0'),
      ('products','seller_name','text'),
      ('products','seller_avatar_url','text'),
      ('products','seller_headline','text'),
      ('products','seller_city','text'),
      ('products','seller_state','text'),
      ('products','approved_at','timestamptz'),
      ('products','banned_at','timestamptz'),
      ('products','removed_at','timestamptz'),
      ('products','created_at','timestamptz not null default now()'),
      ('products','updated_at','timestamptz not null default now()'),
      ('orders','buyer_id','uuid'),
      ('orders','user_id','uuid'),
      ('orders','amount','numeric(14,2) not null default 0'),
      ('orders','shipping_amount','numeric(14,2) not null default 0'),
      ('orders','platform_fee','numeric(14,2) not null default 0'),
      ('orders','status','text not null default ''pending'''),
      ('orders','payment_id','text'),
      ('orders','buyer_name','text not null default '''''),
      ('orders','buyer_phone','text not null default '''''),
      ('orders','address','text not null default '''''),
      ('orders','pincode','text not null default '''''),
      ('orders','shipping_method','text'),
      ('orders','coupon_code','text'),
      ('orders','coupon_discount','numeric(14,2) not null default 0'),
      ('orders','seller_payout_total','numeric(14,2) not null default 0'),
      ('orders','platform_commission_total','numeric(14,2) not null default 0'),
      ('orders','payout_status','text not null default ''pending'''),
      ('orders','expected_payout_at','timestamptz'),
      ('orders','item_count','integer not null default 0'),
      ('orders','created_at','timestamptz not null default now()'),
      ('orders','updated_at','timestamptz not null default now()'),
      ('order_items','order_id','uuid'),
      ('order_items','product_id','uuid'),
      ('order_items','quantity','numeric(12,3) not null default 1'),
      ('order_items','price','numeric(14,2) not null default 0'),
      ('order_items','seller_user_id','uuid'),
      ('order_items','platform_commission','numeric(14,2) not null default 0'),
      ('order_items','seller_amount','numeric(14,2) not null default 0'),
      ('order_items','payout_status','text not null default ''pending_clearance'''),
      ('order_items','created_at','timestamptz not null default now()'),
      ('messages','sender_id','uuid'),
      ('messages','receiver_id','uuid'),
      ('messages','product_id','uuid'),
      ('messages','message','text'),
      ('messages','is_read','boolean not null default false'),
      ('messages','created_at','timestamptz not null default now()'),
      ('messages','updated_at','timestamptz not null default now()'),
      ('reports','reporter_id','uuid'),
      ('reports','reporter_email','text'),
      ('reports','target_type','text not null default ''product'''),
      ('reports','target_id','text'),
      ('reports','product_id','uuid'),
      ('reports','product_title','text'),
      ('reports','seller_id','uuid'),
      ('reports','reason','text'),
      ('reports','status','text not null default ''open'''),
      ('reports','created_at','timestamptz not null default now()'),
      ('reports','updated_at','timestamptz not null default now()'),
      ('contact_messages','user_id','uuid'),
      ('contact_messages','name','text'),
      ('contact_messages','phone','text'),
      ('contact_messages','topic','text not null default ''Other'''),
      ('contact_messages','message','text'),
      ('contact_messages','status','text not null default ''open'''),
      ('contact_messages','created_at','timestamptz not null default now()'),
      ('contact_messages','updated_at','timestamptz not null default now()'),
      ('seller_plans','plan_key','text'),
      ('seller_plans','name','text'),
      ('seller_plans','price','numeric(12,2) not null default 0'),
      ('seller_plans','duration_days','integer not null default 30'),
      ('seller_plans','listing_limit','integer not null default 10'),
      ('seller_plans','boost_days','integer not null default 0'),
      ('seller_plans','badge','text'),
      ('seller_plans','title','text'),
      ('seller_plans','banner','text'),
      ('seller_plans','reward_points','integer not null default 0'),
      ('seller_plans','active','boolean not null default true'),
      ('seller_plans','created_at','timestamptz not null default now()'),
      ('seller_plans','updated_at','timestamptz not null default now()'),
      ('membership_purchases','user_id','uuid'),
      ('membership_purchases','plan_key','text'),
      ('membership_purchases','plan_name','text'),
      ('membership_purchases','amount','numeric(12,2) not null default 0'),
      ('membership_purchases','status','text not null default ''pending'''),
      ('membership_purchases','payment_id','text'),
      ('membership_purchases','starts_at','timestamptz'),
      ('membership_purchases','expires_at','timestamptz'),
      ('membership_purchases','created_at','timestamptz not null default now()'),
      ('membership_purchases','updated_at','timestamptz not null default now()'),
      ('boost_purchases','user_id','uuid'),
      ('boost_purchases','product_id','uuid'),
      ('boost_purchases','amount','numeric(12,2) not null default 0'),
      ('boost_purchases','boost_days','integer not null default 0'),
      ('boost_purchases','status','text not null default ''pending'''),
      ('boost_purchases','payment_id','text'),
      ('boost_purchases','starts_at','timestamptz'),
      ('boost_purchases','expires_at','timestamptz'),
      ('boost_purchases','created_at','timestamptz not null default now()'),
      ('boost_purchases','updated_at','timestamptz not null default now()'),
      ('badge_definitions','badge_key','text'),
      ('badge_definitions','name','text'),
      ('badge_definitions','title','text'),
      ('badge_definitions','tier','text'),
      ('badge_definitions','description','text'),
      ('badge_definitions','rarity','text'),
      ('badge_definitions','sort_order','integer not null default 100'),
      ('badge_definitions','active','boolean not null default true'),
      ('badge_definitions','created_at','timestamptz not null default now()'),
      ('badge_definitions','updated_at','timestamptz not null default now()'),
      ('platform_events','title','text'),
      ('platform_events','description','text'),
      ('platform_events','status','text not null default ''draft'''),
      ('platform_events','starts_at','timestamptz'),
      ('platform_events','ends_at','timestamptz'),
      ('platform_events','reward_badge_key','text'),
      ('platform_events','reward_points','integer not null default 0'),
      ('platform_events','created_at','timestamptz not null default now()'),
      ('platform_events','updated_at','timestamptz not null default now()'),
      ('seller_payout_accounts','user_id','uuid'),
      ('seller_payout_accounts','payout_method','text not null default ''upi'''),
      ('seller_payout_accounts','upi_id','text'),
      ('seller_payout_accounts','account_holder_name','text'),
      ('seller_payout_accounts','bank_name','text'),
      ('seller_payout_accounts','account_number','text'),
      ('seller_payout_accounts','ifsc','text'),
      ('seller_payout_accounts','created_at','timestamptz not null default now()'),
      ('seller_payout_accounts','updated_at','timestamptz not null default now()'),
      ('seller_balances','user_id','uuid'),
      ('seller_balances','available_balance','numeric(14,2) not null default 0'),
      ('seller_balances','pending_balance','numeric(14,2) not null default 0'),
      ('seller_balances','paid_balance','numeric(14,2) not null default 0'),
      ('seller_balances','platform_fee_total','numeric(14,2) not null default 0'),
      ('seller_balances','last_order_at','timestamptz'),
      ('seller_balances','created_at','timestamptz not null default now()'),
      ('seller_balances','updated_at','timestamptz not null default now()'),
      ('seller_payout_requests','user_id','uuid'),
      ('seller_payout_requests','amount','numeric(14,2) not null default 0'),
      ('seller_payout_requests','status','text not null default ''requested'''),
      ('seller_payout_requests','payout_method','text not null default ''upi'''),
      ('seller_payout_requests','upi_id','text'),
      ('seller_payout_requests','account_holder_name','text'),
      ('seller_payout_requests','bank_name','text'),
      ('seller_payout_requests','account_number','text'),
      ('seller_payout_requests','ifsc','text'),
      ('seller_payout_requests','paid_at','timestamptz'),
      ('seller_payout_requests','created_at','timestamptz not null default now()'),
      ('seller_payout_requests','updated_at','timestamptz not null default now()'),
      ('seller_ledger','seller_id','uuid'),
      ('seller_ledger','order_id','uuid'),
      ('seller_ledger','product_id','uuid'),
      ('seller_ledger','gross_amount','numeric(14,2) not null default 0'),
      ('seller_ledger','platform_fee','numeric(14,2) not null default 0'),
      ('seller_ledger','seller_amount','numeric(14,2) not null default 0'),
      ('seller_ledger','status','text not null default ''pending_clearance'''),
      ('seller_ledger','available_on','date'),
      ('seller_ledger','notes','text'),
      ('seller_ledger','created_at','timestamptz not null default now()'),
      ('seller_ledger','updated_at','timestamptz not null default now()'),
      ('site_carousel_slides','title','text'),
      ('site_carousel_slides','subtitle','text'),
      ('site_carousel_slides','image_url','text'),
      ('site_carousel_slides','cta_text','text not null default ''Open'''),
      ('site_carousel_slides','cta_route','text not null default ''market'''),
      ('site_carousel_slides','sort_order','integer not null default 10'),
      ('site_carousel_slides','active','boolean not null default true'),
      ('site_carousel_slides','created_at','timestamptz not null default now()'),
      ('site_carousel_slides','updated_at','timestamptz not null default now()'),
      ('admin_notifications','type','text'),
      ('admin_notifications','subject','text'),
      ('admin_notifications','body','text'),
      ('admin_notifications','payload','jsonb not null default ''{}''::jsonb'),
      ('admin_notifications','status','text not null default ''unread'''),
      ('admin_notifications','priority','text not null default ''important'''),
      ('admin_notifications','important','boolean not null default true'),
      ('admin_notifications','admin_email','text'),
      ('admin_notifications','email_to','text'),
      ('admin_notifications','email_sent','boolean not null default false'),
      ('admin_notifications','source','text not null default ''harvester-parts-website'''),
      ('admin_notifications','created_at','timestamptz not null default now()'),
      ('admin_notifications','updated_at','timestamptz not null default now()'),
      ('site_analytics','event_type','text not null default ''page_view'''),
      ('site_analytics','route','text not null default ''home'''),
      ('site_analytics','product_id','text'),
      ('site_analytics','user_id','uuid'),
      ('site_analytics','session_id','text'),
      ('site_analytics','lang','text default ''en'''),
      ('site_analytics','device','text default ''desktop'''),
      ('site_analytics','referrer','text default ''direct'''),
      ('site_analytics','user_agent','text'),
      ('site_analytics','metadata','jsonb not null default ''{}''::jsonb'),
      ('site_analytics','created_at','timestamptz not null default now()'),
      ('seller_reviews','seller_id','uuid'),
      ('seller_reviews','reviewer_id','uuid'),
      ('seller_reviews','rating','integer'),
      ('seller_reviews','comment','text not null default '''''),
      ('seller_reviews','status','text not null default ''approved'''),
      ('seller_reviews','created_at','timestamptz not null default now()'),
      ('seller_reviews','updated_at','timestamptz not null default now()')
    ) as v(table_name, column_name, column_definition)
  loop
    execute format(
      'alter table public.%I add column if not exists %I %s',
      r.table_name,
      r.column_name,
      r.column_definition
    );
  end loop;
end $$;

-- Required uniqueness for upsert operations used by the website.
create unique index if not exists users_auth_id_uidx on public.users(auth_id);
create unique index if not exists users_user_uid_uidx on public.users(user_uid) where user_uid is not null;
create unique index if not exists sellers_user_id_uidx on public.sellers(user_id);
create unique index if not exists seller_payout_accounts_user_id_uidx on public.seller_payout_accounts(user_id);
create unique index if not exists seller_balances_user_id_uidx on public.seller_balances(user_id);
create unique index if not exists seller_reviews_pair_uidx on public.seller_reviews(seller_id, reviewer_id);
create unique index if not exists seller_plans_key_uidx on public.seller_plans(plan_key);

-- Add missing relationships to older databases. NOT VALID preserves existing rows
-- while enforcing the relationship for new writes. Any incompatible legacy column
-- is reported as a NOTICE instead of deleting or rewriting data.
do $$
declare
  r record;
begin
  for r in
    select * from (values
      ('users','users_auth_id_fkey','foreign key (auth_id) references auth.users(id) on delete cascade'),
      ('sellers','sellers_user_id_fkey','foreign key (user_id) references public.users(auth_id) on delete cascade'),
      ('products','products_user_id_fkey','foreign key (user_id) references public.users(auth_id) on delete cascade'),
      ('products','products_seller_id_fkey','foreign key (seller_id) references public.sellers(id) on delete set null'),
      ('orders','orders_buyer_id_fkey','foreign key (buyer_id) references public.users(auth_id) on delete restrict'),
      ('orders','orders_user_id_fkey','foreign key (user_id) references public.users(auth_id) on delete restrict'),
      ('order_items','order_items_order_id_fkey','foreign key (order_id) references public.orders(id) on delete cascade'),
      ('order_items','order_items_product_id_fkey','foreign key (product_id) references public.products(id) on delete set null'),
      ('order_items','order_items_seller_user_id_fkey','foreign key (seller_user_id) references public.users(auth_id) on delete set null'),
      ('messages','messages_sender_id_fkey','foreign key (sender_id) references public.users(auth_id) on delete cascade'),
      ('messages','messages_receiver_id_fkey','foreign key (receiver_id) references public.users(auth_id) on delete cascade'),
      ('messages','messages_product_id_fkey','foreign key (product_id) references public.products(id) on delete set null'),
      ('reports','reports_reporter_id_fkey','foreign key (reporter_id) references public.users(auth_id) on delete cascade'),
      ('reports','reports_product_id_fkey','foreign key (product_id) references public.products(id) on delete set null'),
      ('reports','reports_seller_id_fkey','foreign key (seller_id) references public.users(auth_id) on delete set null'),
      ('contact_messages','contact_messages_user_id_fkey','foreign key (user_id) references public.users(auth_id) on delete set null'),
      ('membership_purchases','membership_purchases_user_id_fkey','foreign key (user_id) references public.users(auth_id) on delete cascade'),
      ('boost_purchases','boost_purchases_user_id_fkey','foreign key (user_id) references public.users(auth_id) on delete cascade'),
      ('boost_purchases','boost_purchases_product_id_fkey','foreign key (product_id) references public.products(id) on delete set null'),
      ('platform_events','platform_events_reward_badge_key_fkey','foreign key (reward_badge_key) references public.badge_definitions(badge_key) on delete set null'),
      ('seller_payout_accounts','seller_payout_accounts_user_id_fkey','foreign key (user_id) references public.users(auth_id) on delete cascade'),
      ('seller_balances','seller_balances_user_id_fkey','foreign key (user_id) references public.users(auth_id) on delete cascade'),
      ('seller_payout_requests','seller_payout_requests_user_id_fkey','foreign key (user_id) references public.users(auth_id) on delete cascade'),
      ('seller_ledger','seller_ledger_seller_id_fkey','foreign key (seller_id) references public.users(auth_id) on delete cascade'),
      ('seller_ledger','seller_ledger_order_id_fkey','foreign key (order_id) references public.orders(id) on delete set null'),
      ('seller_ledger','seller_ledger_product_id_fkey','foreign key (product_id) references public.products(id) on delete set null'),
      ('seller_reviews','seller_reviews_seller_id_fkey','foreign key (seller_id) references public.users(auth_id) on delete cascade'),
      ('seller_reviews','seller_reviews_reviewer_id_fkey','foreign key (reviewer_id) references public.users(auth_id) on delete cascade')
    ) as v(table_name, constraint_name, constraint_definition)
  loop
    if not exists (
      select 1 from pg_constraint
      where conname = r.constraint_name
        and conrelid = format('public.%I', r.table_name)::regclass
    ) then
      begin
        execute format(
          'alter table public.%I add constraint %I %s not valid',
          r.table_name,
          r.constraint_name,
          r.constraint_definition
        );
      exception when others then
        raise notice 'Relationship % could not be added: %', r.constraint_name, sqlerrm;
      end;
    end if;
  end loop;
end $$;

-- Useful query indexes.
create index if not exists products_status_created_idx on public.products(status, created_at desc);
create index if not exists products_user_created_idx on public.products(user_id, created_at desc);
create index if not exists products_category_idx on public.products(category);
create index if not exists products_location_idx on public.products(state, city);
create index if not exists orders_buyer_created_idx on public.orders(buyer_id, created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists messages_sender_created_idx on public.messages(sender_id, created_at desc);
create index if not exists messages_receiver_created_idx on public.messages(receiver_id, created_at desc);
create index if not exists messages_product_idx on public.messages(product_id);
create index if not exists reports_status_created_idx on public.reports(status, created_at desc);
create index if not exists membership_user_created_idx on public.membership_purchases(user_id, created_at desc);
create index if not exists payout_requests_user_created_idx on public.seller_payout_requests(user_id, created_at desc);
create index if not exists seller_ledger_seller_created_idx on public.seller_ledger(seller_id, created_at desc);
create index if not exists seller_ledger_order_idx on public.seller_ledger(order_id);
create index if not exists site_slides_order_idx on public.site_carousel_slides(active, sort_order, created_at desc);
create index if not exists admin_notifications_created_idx on public.admin_notifications(created_at desc);
create index if not exists site_analytics_created_idx on public.site_analytics(created_at desc);
create index if not exists site_analytics_session_idx on public.site_analytics(session_id, created_at desc);
create index if not exists site_analytics_route_idx on public.site_analytics(route, created_at desc);
create index if not exists seller_reviews_seller_created_idx on public.seller_reviews(seller_id, created_at desc);

-- -----------------------------------------------------------------------------
-- 5. Security helpers, auth profile creation and automatic sync
-- -----------------------------------------------------------------------------

create or replace function public.is_hp_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    lower(coalesce(auth.jwt() ->> 'email', '')) = lower('kiratveersinghralhan@gmail.com')
    or exists (
      select 1
      from public.users u
      where u.auth_id = auth.uid()
        and (
          u.role = 'admin'
          or lower(coalesce(u.email, '')) = lower('kiratveersinghralhan@gmail.com')
        )
    );
$$;

revoke all on function public.is_hp_admin() from public;
grant execute on function public.is_hp_admin() to anon, authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users','sellers','products','orders','messages','reports','contact_messages',
    'seller_plans','membership_purchases','boost_purchases','badge_definitions',
    'platform_events','seller_payout_accounts','seller_balances',
    'seller_payout_requests','seller_ledger','site_carousel_slides',
    'admin_notifications','seller_reviews'
  ]
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name,
      table_name
    );
  end loop;
end $$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  is_owner boolean := lower(coalesce(new.email, '')) = lower('kiratveersinghralhan@gmail.com');
begin
  insert into public.users (
    auth_id, email, phone, full_name, role, user_uid,
    rank_key, rank_title, badge_key, badge_title, banner_key, banner_title,
    title_prefix, is_founder, founder_number, points
  ) values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.phone, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', ''),
    case when is_owner then 'admin' else 'user' end,
    'HP-' || upper(substr(replace(new.id::text, '-', ''), 1, 8)),
    case when is_owner then 'founder' else 'starter' end,
    case when is_owner then 'Founder 1 of 1' else 'Farm Starter' end,
    case when is_owner then 'founder_1_of_1' else 'buyer_member' end,
    case when is_owner then 'Founder 1 of 1' else 'Member' end,
    case when is_owner then 'founder_1_of_1' else null end,
    case when is_owner then 'Original Founder - One of One' else null end,
    case when is_owner then 'Platform Founder' else null end,
    is_owner,
    case when is_owner then 1 else null end,
    case when is_owner then 999999 else 0 end
  )
  on conflict (auth_id) do update set
    email = excluded.email,
    phone = case when excluded.phone <> '' then excluded.phone else public.users.phone end,
    full_name = case when public.users.full_name = '' then excluded.full_name else public.users.full_name end,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_hp on auth.users;
create trigger on_auth_user_created_hp
after insert or update of email, phone, raw_user_meta_data on auth.users
for each row execute function public.handle_new_auth_user();

-- Backfill profiles for Auth users that existed before this setup.
insert into public.users (auth_id, email, phone, full_name, role, user_uid)
select
  au.id,
  coalesce(au.email, ''),
  coalesce(au.phone, ''),
  coalesce(au.raw_user_meta_data ->> 'full_name', au.raw_user_meta_data ->> 'name', ''),
  case when lower(coalesce(au.email, '')) = lower('kiratveersinghralhan@gmail.com') then 'admin' else 'user' end,
  'HP-' || upper(substr(replace(au.id::text, '-', ''), 1, 8))
from auth.users au
on conflict (auth_id) do nothing;

update public.users
set
  role = 'admin',
  rank_key = 'founder',
  rank_title = 'Founder 1 of 1',
  badge_key = 'founder_1_of_1',
  badge_title = 'Founder 1 of 1',
  banner_key = 'founder_1_of_1',
  banner_title = 'Original Founder - One of One',
  title_prefix = 'Platform Founder',
  is_founder = true,
  founder_number = 1,
  points = 999999,
  updated_at = now()
where lower(email) = lower('kiratveersinghralhan@gmail.com');

create or replace function public.protect_user_privileged_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null and not public.is_hp_admin() then
    if tg_op = 'INSERT' then
      new.role := 'user';
      new.is_founder := false;
      new.founder_number := null;
    else
      new.role := old.role;
      new.is_founder := old.is_founder;
      new.founder_number := old.founder_number;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_users_privileged_hp on public.users;
create trigger protect_users_privileged_hp
before insert or update on public.users
for each row execute function public.protect_user_privileged_fields();

create or replace function public.protect_seller_review_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_hp_admin() then
    if tg_op = 'INSERT' then
      new.status := 'approved';
    else
      new.status := old.status;
      new.seller_id := old.seller_id;
      new.reviewer_id := old.reviewer_id;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_seller_reviews_hp on public.seller_reviews;
create trigger protect_seller_reviews_hp
before insert or update on public.seller_reviews
for each row execute function public.protect_seller_review_fields();

create or replace function public.protect_seller_verification_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is not null and not public.is_hp_admin() then
    if tg_op = 'INSERT' then
      new.status := 'pending';
      new.verification_status := 'pending';
      new.approved_at := null;
      new.banned_at := null;
    else
      new.status := old.status;
      new.verification_status := old.verification_status;
      new.approved_at := old.approved_at;
      new.banned_at := old.banned_at;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_seller_status_hp on public.sellers;
create trigger protect_seller_status_hp
before insert or update on public.sellers
for each row execute function public.protect_seller_verification_status();

-- Public profile snapshots on products keep seller names/photos current without
-- exposing private users-table columns.
create or replace function public.fill_product_public_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  select u.full_name, u.avatar_url, u.headline, u.city, u.state
  into new.seller_name, new.seller_avatar_url, new.seller_headline, new.seller_city, new.seller_state
  from public.users u
  where u.auth_id = new.user_id;
  return new;
end;
$$;

drop trigger if exists fill_product_profile_hp on public.products;
create trigger fill_product_profile_hp
before insert or update of user_id on public.products
for each row execute function public.fill_product_public_profile();

create or replace function public.sync_user_public_profile_to_products()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.products
  set
    seller_name = new.full_name,
    seller_avatar_url = new.avatar_url,
    seller_headline = new.headline,
    seller_city = new.city,
    seller_state = new.state,
    updated_at = now()
  where user_id = new.auth_id;
  return new;
end;
$$;

drop trigger if exists sync_public_profile_products_hp on public.users;
create trigger sync_public_profile_products_hp
after update of full_name, avatar_url, headline, city, state on public.users
for each row execute function public.sync_user_public_profile_to_products();

update public.products p
set
  seller_name = u.full_name,
  seller_avatar_url = u.avatar_url,
  seller_headline = u.headline,
  seller_city = u.city,
  seller_state = u.state
from public.users u
where u.auth_id = p.user_id;

create or replace function public.refresh_seller_balance_from_ledger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_seller uuid;
begin
  target_seller := case when tg_op = 'DELETE' then old.seller_id else new.seller_id end;
  insert into public.seller_balances (
    user_id, available_balance, pending_balance, paid_balance,
    platform_fee_total, last_order_at, updated_at
  )
  select
    target_seller,
    coalesce(sum(l.seller_amount) filter (where l.status in ('pending_clearance','available','payout_requested')), 0),
    coalesce(sum(l.seller_amount) filter (where l.status in ('pending_clearance','available','payout_requested')), 0),
    coalesce(sum(l.seller_amount) filter (where l.status = 'paid'), 0),
    coalesce(sum(l.platform_fee), 0),
    max(l.created_at),
    now()
  from public.seller_ledger l
  where l.seller_id = target_seller
  on conflict (user_id) do update set
    available_balance = excluded.available_balance,
    pending_balance = excluded.pending_balance,
    paid_balance = excluded.paid_balance,
    platform_fee_total = excluded.platform_fee_total,
    last_order_at = excluded.last_order_at,
    updated_at = now();
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists refresh_seller_balance_hp on public.seller_ledger;
create trigger refresh_seller_balance_hp
after insert or update or delete on public.seller_ledger
for each row execute function public.refresh_seller_balance_from_ledger();

-- Commission helpers match the website launch slabs.
create or replace function public.hp_commission_rate(order_value numeric)
returns numeric
language sql
immutable
as $$
  select case
    when coalesce(order_value, 0) < 5000 then 0.035
    when order_value < 10000 then 0.030
    when order_value < 100000 then 0.025
    when order_value < 300000 then 0.020
    when order_value < 1000000 then 0.015
    else 0.010
  end;
$$;

create or replace function public.hp_commission_amount(order_value numeric)
returns numeric
language sql
immutable
as $$
  select round(greatest(coalesce(order_value, 0), 0) * public.hp_commission_rate(order_value), 2);
$$;

-- Privacy-safe seller view. Email, phone, gender, documents, bank details and
-- addresses are intentionally excluded.
create or replace view public.public_seller_profiles
with (security_barrier = true)
as
select
  u.auth_id,
  u.full_name,
  u.avatar_url,
  u.headline,
  u.bio,
  u.city,
  u.state,
  u.business_type,
  u.experience_years,
  u.badge_title,
  u.rank_title,
  u.role,
  u.points,
  u.profile_completed,
  u.created_at
from public.users u;

grant select on public.public_seller_profiles to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 6. Row Level Security and table privileges
-- -----------------------------------------------------------------------------

do $$
declare
  p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = any(array[
        'users','sellers','products','orders','order_items','messages','reports',
        'contact_messages','seller_plans','membership_purchases','boost_purchases',
        'badge_definitions','platform_events','seller_payout_accounts','seller_balances',
        'seller_payout_requests','seller_ledger','site_carousel_slides',
        'admin_notifications','site_analytics','seller_reviews'
      ])
  loop
    execute format('drop policy if exists %I on public.%I', p.policyname, p.tablename);
  end loop;
end $$;

alter table public.users enable row level security;
alter table public.sellers enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.messages enable row level security;
alter table public.reports enable row level security;
alter table public.contact_messages enable row level security;
alter table public.seller_plans enable row level security;
alter table public.membership_purchases enable row level security;
alter table public.boost_purchases enable row level security;
alter table public.badge_definitions enable row level security;
alter table public.platform_events enable row level security;
alter table public.seller_payout_accounts enable row level security;
alter table public.seller_balances enable row level security;
alter table public.seller_payout_requests enable row level security;
alter table public.seller_ledger enable row level security;
alter table public.site_carousel_slides enable row level security;
alter table public.admin_notifications enable row level security;
alter table public.site_analytics enable row level security;
alter table public.seller_reviews enable row level security;

revoke all on table public.users, public.sellers, public.products, public.orders,
  public.order_items, public.messages, public.reports, public.contact_messages,
  public.seller_plans, public.membership_purchases, public.boost_purchases,
  public.badge_definitions, public.platform_events, public.seller_payout_accounts,
  public.seller_balances, public.seller_payout_requests, public.seller_ledger,
  public.site_carousel_slides, public.admin_notifications, public.site_analytics,
  public.seller_reviews from anon, authenticated;

grant select on public.users, public.sellers, public.products,
  public.seller_plans, public.badge_definitions, public.platform_events,
  public.site_carousel_slides, public.seller_reviews to anon, authenticated;
grant select on public.orders, public.order_items, public.messages, public.reports,
  public.contact_messages, public.membership_purchases, public.boost_purchases,
  public.seller_payout_accounts, public.seller_balances,
  public.seller_payout_requests, public.seller_ledger, public.admin_notifications,
  public.site_analytics to authenticated;
grant insert, update on public.users, public.sellers, public.products,
  public.messages, public.reports, public.membership_purchases, public.boost_purchases,
  public.seller_payout_accounts, public.seller_payout_requests,
  public.seller_ledger, public.seller_reviews to authenticated;
grant delete on public.products, public.messages to authenticated;
grant insert, delete on public.orders to authenticated;
grant insert on public.order_items to authenticated;
grant update on public.orders, public.order_items, public.reports,
  public.contact_messages, public.seller_balances, public.seller_payout_requests,
  public.site_carousel_slides, public.admin_notifications to authenticated;
grant insert, update, delete on public.seller_plans, public.badge_definitions,
  public.platform_events, public.site_carousel_slides to authenticated;
grant insert on public.contact_messages, public.admin_notifications,
  public.site_analytics to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

create policy users_select_own_or_admin
on public.users for select to authenticated
using (auth_id = auth.uid() or public.is_hp_admin());

create policy users_insert_own_or_admin
on public.users for insert to authenticated
with check (auth_id = auth.uid() or public.is_hp_admin());

create policy users_update_own_or_admin
on public.users for update to authenticated
using (auth_id = auth.uid() or public.is_hp_admin())
with check (auth_id = auth.uid() or public.is_hp_admin());

create policy sellers_select_own_or_admin
on public.sellers for select to authenticated
using (user_id = auth.uid() or public.is_hp_admin());

create policy sellers_insert_own_or_admin
on public.sellers for insert to authenticated
with check (user_id = auth.uid() or public.is_hp_admin());

create policy sellers_update_own_or_admin
on public.sellers for update to authenticated
using (user_id = auth.uid() or public.is_hp_admin())
with check (user_id = auth.uid() or public.is_hp_admin());

create policy products_public_read
on public.products for select to anon, authenticated
using (status = 'approved' or user_id = auth.uid() or public.is_hp_admin());

create policy products_insert_approved_seller_or_admin
on public.products for insert to authenticated
with check (
  public.is_hp_admin()
  or (
    user_id = auth.uid()
    and exists (
      select 1 from public.sellers s
      where s.user_id = auth.uid() and s.status = 'approved'
    )
  )
);

create policy products_update_owner_or_admin
on public.products for update to authenticated
using (user_id = auth.uid() or public.is_hp_admin())
with check (user_id = auth.uid() or public.is_hp_admin());

create policy products_delete_owner_or_admin
on public.products for delete to authenticated
using (user_id = auth.uid() or public.is_hp_admin());

create policy orders_select_buyer_or_admin
on public.orders for select to authenticated
using (buyer_id = auth.uid() or user_id = auth.uid() or public.is_hp_admin());

create policy orders_insert_buyer
on public.orders for insert to authenticated
with check (
  public.is_hp_admin()
  or (buyer_id = auth.uid() and coalesce(user_id, auth.uid()) = auth.uid())
);

create policy orders_update_admin
on public.orders for update to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy orders_delete_pending_buyer_or_admin
on public.orders for delete to authenticated
using (
  public.is_hp_admin()
  or ((buyer_id = auth.uid() or user_id = auth.uid()) and status in ('pending','cancelled'))
);

create policy order_items_select_participant_or_admin
on public.order_items for select to authenticated
using (
  seller_user_id = auth.uid()
  or public.is_hp_admin()
  or exists (
    select 1 from public.orders o
    where o.id = order_id and (o.buyer_id = auth.uid() or o.user_id = auth.uid())
  )
);

create policy order_items_insert_order_buyer_or_admin
on public.order_items for insert to authenticated
with check (
  public.is_hp_admin()
  or exists (
    select 1 from public.orders o
    where o.id = order_id and (o.buyer_id = auth.uid() or o.user_id = auth.uid())
  )
);

create policy order_items_update_admin
on public.order_items for update to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy messages_select_participants
on public.messages for select to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid() or public.is_hp_admin());

create policy messages_insert_sender
on public.messages for insert to authenticated
with check (sender_id = auth.uid() or public.is_hp_admin());

create policy messages_update_receiver_or_admin
on public.messages for update to authenticated
using (receiver_id = auth.uid() or public.is_hp_admin())
with check (receiver_id = auth.uid() or public.is_hp_admin());

create policy messages_delete_participant_or_admin
on public.messages for delete to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid() or public.is_hp_admin());

create policy reports_select_reporter_or_admin
on public.reports for select to authenticated
using (reporter_id = auth.uid() or public.is_hp_admin());

create policy reports_insert_reporter
on public.reports for insert to authenticated
with check (reporter_id = auth.uid() and char_length(reason) between 3 and 2000);

create policy reports_update_admin
on public.reports for update to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy contact_insert_public
on public.contact_messages for insert to anon, authenticated
with check (
  char_length(name) between 2 and 120
  and char_length(message) between 3 and 5000
);

create policy contact_select_admin
on public.contact_messages for select to authenticated
using (public.is_hp_admin());

create policy contact_update_admin
on public.contact_messages for update to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy seller_plans_public_read
on public.seller_plans for select to anon, authenticated
using (active or public.is_hp_admin());

create policy seller_plans_admin_write
on public.seller_plans for all to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy membership_select_own_or_admin
on public.membership_purchases for select to authenticated
using (user_id = auth.uid() or public.is_hp_admin());

create policy membership_insert_own_or_admin
on public.membership_purchases for insert to authenticated
with check (user_id = auth.uid() or public.is_hp_admin());

create policy membership_update_admin
on public.membership_purchases for update to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy boosts_select_own_or_admin
on public.boost_purchases for select to authenticated
using (user_id = auth.uid() or public.is_hp_admin());

create policy boosts_insert_own_or_admin
on public.boost_purchases for insert to authenticated
with check (user_id = auth.uid() or public.is_hp_admin());

create policy boosts_update_admin
on public.boost_purchases for update to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy badges_public_read
on public.badge_definitions for select to anon, authenticated
using (active or public.is_hp_admin());

create policy badges_admin_write
on public.badge_definitions for all to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy events_public_read
on public.platform_events for select to anon, authenticated
using (status in ('active','published','completed') or public.is_hp_admin());

create policy events_admin_write
on public.platform_events for all to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy payout_accounts_own_or_admin
on public.seller_payout_accounts for all to authenticated
using (user_id = auth.uid() or public.is_hp_admin())
with check (user_id = auth.uid() or public.is_hp_admin());

create policy seller_balances_select_own_or_admin
on public.seller_balances for select to authenticated
using (user_id = auth.uid() or public.is_hp_admin());

create policy seller_balances_update_admin
on public.seller_balances for update to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy payout_requests_select_own_or_admin
on public.seller_payout_requests for select to authenticated
using (user_id = auth.uid() or public.is_hp_admin());

create policy payout_requests_insert_own
on public.seller_payout_requests for insert to authenticated
with check (user_id = auth.uid() and amount > 0);

create policy payout_requests_update_admin
on public.seller_payout_requests for update to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy seller_ledger_select_seller_or_admin
on public.seller_ledger for select to authenticated
using (seller_id = auth.uid() or public.is_hp_admin());

create policy seller_ledger_insert_order_buyer_or_admin
on public.seller_ledger for insert to authenticated
with check (
  public.is_hp_admin()
  or exists (
    select 1 from public.orders o
    where o.id = order_id and (o.buyer_id = auth.uid() or o.user_id = auth.uid())
  )
);

create policy seller_ledger_update_seller_or_admin
on public.seller_ledger for update to authenticated
using (seller_id = auth.uid() or public.is_hp_admin())
with check (seller_id = auth.uid() or public.is_hp_admin());

create policy slides_public_read
on public.site_carousel_slides for select to anon, authenticated
using (active or public.is_hp_admin());

create policy slides_admin_write
on public.site_carousel_slides for all to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy notifications_public_insert
on public.admin_notifications for insert to anon, authenticated
with check (
  char_length(type) between 2 and 80
  and char_length(subject) between 2 and 240
  and char_length(body) between 2 and 10000
);

create policy notifications_admin_read
on public.admin_notifications for select to authenticated
using (public.is_hp_admin());

create policy notifications_admin_update
on public.admin_notifications for update to authenticated
using (public.is_hp_admin())
with check (public.is_hp_admin());

create policy analytics_public_insert
on public.site_analytics for insert to anon, authenticated
with check (
  char_length(session_id) between 6 and 120
  and char_length(event_type) between 2 and 40
  and char_length(route) between 1 and 80
);

create policy analytics_admin_read
on public.site_analytics for select to authenticated
using (public.is_hp_admin());

create policy reviews_public_read
on public.seller_reviews for select to anon, authenticated
using (
  status = 'approved'
  or reviewer_id = auth.uid()
  or seller_id = auth.uid()
  or public.is_hp_admin()
);

create policy reviews_insert_reviewer
on public.seller_reviews for insert to authenticated
with check (reviewer_id = auth.uid() and seller_id <> auth.uid());

create policy reviews_update_reviewer_or_admin
on public.seller_reviews for update to authenticated
using (reviewer_id = auth.uid() or public.is_hp_admin())
with check (reviewer_id = auth.uid() or public.is_hp_admin());

-- -----------------------------------------------------------------------------
-- 7. Storage buckets and file policies
-- -----------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'profile-avatars', 'profile-avatars', true, 6291456,
    array['image/jpeg','image/png','image/webp','image/avif','image/heic','image/heif']
  ),
  (
    'product-images', 'product-images', true, 52428800,
    array[
      'image/jpeg','image/png','image/webp','image/avif','image/gif','image/heic','image/heif',
      'video/mp4','video/webm','video/quicktime','video/x-m4v'
    ]
  ),
  (
    'verification-docs', 'verification-docs', false, 12582912,
    array['image/jpeg','image/png','image/webp','image/heic','image/heif','application/pdf']
  )
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Remove only older policies that mention Harvester Parts buckets. Policies for
-- unrelated Storage buckets in the same Supabase project are left untouched.
do $$
declare
  p record;
begin
  for p in
    select policyname
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and (
        coalesce(qual, '') || ' ' || coalesce(with_check, '')
      ) ~ '(profile-avatars|product-images|verification-docs)'
  loop
    execute format('drop policy if exists %I on storage.objects', p.policyname);
  end loop;
end $$;

drop policy if exists hp_profile_avatars_public_read on storage.objects;
drop policy if exists hp_profile_avatars_owner_insert on storage.objects;
drop policy if exists hp_profile_avatars_owner_update on storage.objects;
drop policy if exists hp_profile_avatars_owner_delete on storage.objects;
drop policy if exists hp_product_media_public_read on storage.objects;
drop policy if exists hp_product_media_owner_insert on storage.objects;
drop policy if exists hp_product_media_owner_update on storage.objects;
drop policy if exists hp_product_media_owner_delete on storage.objects;
drop policy if exists hp_verification_docs_owner_insert on storage.objects;
drop policy if exists hp_verification_docs_owner_read on storage.objects;
drop policy if exists hp_verification_docs_owner_update on storage.objects;
drop policy if exists hp_verification_docs_owner_delete on storage.objects;
drop policy if exists hp_verification_docs_admin_read on storage.objects;

create policy hp_profile_avatars_public_read
on storage.objects for select to public
using (bucket_id = 'profile-avatars');

create policy hp_profile_avatars_owner_insert
on storage.objects for insert to authenticated
with check (
  bucket_id = 'profile-avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy hp_profile_avatars_owner_update
on storage.objects for update to authenticated
using (bucket_id = 'profile-avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'profile-avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy hp_profile_avatars_owner_delete
on storage.objects for delete to authenticated
using (bucket_id = 'profile-avatars' and (storage.foldername(name))[1] = auth.uid()::text);

create policy hp_product_media_public_read
on storage.objects for select to public
using (bucket_id = 'product-images');

create policy hp_product_media_owner_insert
on storage.objects for insert to authenticated
with check (
  bucket_id = 'product-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy hp_product_media_owner_update
on storage.objects for update to authenticated
using (bucket_id = 'product-images' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'product-images' and (storage.foldername(name))[1] = auth.uid()::text);

create policy hp_product_media_owner_delete
on storage.objects for delete to authenticated
using (bucket_id = 'product-images' and (storage.foldername(name))[1] = auth.uid()::text);

create policy hp_verification_docs_owner_insert
on storage.objects for insert to authenticated
with check (
  bucket_id = 'verification-docs'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy hp_verification_docs_owner_read
on storage.objects for select to authenticated
using (
  bucket_id = 'verification-docs'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy hp_verification_docs_owner_update
on storage.objects for update to authenticated
using (bucket_id = 'verification-docs' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'verification-docs' and (storage.foldername(name))[1] = auth.uid()::text);

create policy hp_verification_docs_owner_delete
on storage.objects for delete to authenticated
using (bucket_id = 'verification-docs' and (storage.foldername(name))[1] = auth.uid()::text);

create policy hp_verification_docs_admin_read
on storage.objects for select to authenticated
using (bucket_id = 'verification-docs' and public.is_hp_admin());

-- -----------------------------------------------------------------------------
-- 8. Realtime tables
-- -----------------------------------------------------------------------------

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users','sellers','products','orders','messages','membership_purchases',
    'seller_ledger','seller_balances','seller_payout_requests',
    'site_carousel_slides','seller_reviews','admin_notifications'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = table_name
    ) then
      begin
        execute format('alter publication supabase_realtime add table public.%I', table_name);
      exception
        when duplicate_object then null;
        when undefined_object then
          raise notice 'supabase_realtime publication is unavailable; enable Realtime in the dashboard.';
      end;
    end if;
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- 9. Default plans and badge definitions
-- -----------------------------------------------------------------------------

insert into public.seller_plans (
  plan_key, name, price, duration_days, listing_limit, boost_days,
  badge, title, banner, reward_points, active
)
values
  ('starter_19','Starter Offer',19,15,25,3,'Starter Offer','Starter Seller','New Seller Offer',180,true),
  ('growth_49','Growth Seller',49,30,75,12,'Growth Seller','Growth Seller','Growth Seller Banner',650,true),
  ('dealer_99','Dealer Plus',99,45,180,35,'Dealer Plus','Dealer Plus','Dealer Plus Banner',1500,true),
  ('partner_199','Market Partner',199,75,500,90,'Market Partner','Market Partner','Market Partner Banner',3600,true),
  ('leader_499','Market Leader',499,120,999999,250,'Market Leader','Market Leader','Market Leader Banner',9000,true)
on conflict (plan_key) do update set
  name = excluded.name,
  price = excluded.price,
  duration_days = excluded.duration_days,
  listing_limit = excluded.listing_limit,
  boost_days = excluded.boost_days,
  badge = excluded.badge,
  title = excluded.title,
  banner = excluded.banner,
  reward_points = excluded.reward_points,
  active = excluded.active,
  updated_at = now();

insert into public.badge_definitions (
  badge_key, name, title, tier, description, rarity, sort_order, active
)
values
  ('founder_1_of_1','Founder 1 of 1','Platform Founder','founder','One owner. One original account. Permanent identity.','1 OF 1',1,true),
  ('original_builder','Original Builder','Built the Market','founder','Reserved founder-series badge for the platform creator.','FOUNDER',2,true),
  ('admin_crown','Admin Authority','Control Center','admin','Can approve, reject, ban and protect platform quality.','UNIQUE',3,true),
  ('market_guardian','Market Guardian','Safety Admin','admin','Protects buyers, sellers, documents and marketplace trust.','ADMIN',4,true),
  ('verified_seller','Verified Seller','Trusted Seller','green','Documents approved and seller profile reviewed.','VERIFIED',10,true),
  ('first_listing','First Listing','Marketplace Starter','bronze','Posted the first product for admin approval.','STARTER',20,true),
  ('growth_seller','Growth Seller','Listing Builder','silver','Multiple listings created and seller activity started.','GROWTH',30,true),
  ('trusted_dealer','Trusted Dealer','Dealer Rank','gold','High approved catalog activity and trust signals.','HIGH',40,true),
  ('premium_member','Premium Member','Plan Holder','premium','Membership plan active with extra rewards and visibility.','PLAN',50,true),
  ('event_champion','Event Champion','Campaign Winner','event','Limited reward for future leaderboard events.','EVENT',60,true),
  ('buyer_member','Buyer Member','Market Member','base','Joined Harvester Parts marketplace.','MEMBER',100,true)
on conflict (badge_key) do update set
  name = excluded.name,
  title = excluded.title,
  tier = excluded.tier,
  description = excluded.description,
  rarity = excluded.rarity,
  sort_order = excluded.sort_order,
  active = excluded.active,
  updated_at = now();

-- -----------------------------------------------------------------------------
-- 10. Setup health report
-- -----------------------------------------------------------------------------

create or replace function public.hp_schema_check()
returns table(category text, object_name text, status text)
language sql
stable
security definer
set search_path = public, storage
as $$
  with expected_tables(name) as (
    values
      ('users'),('sellers'),('products'),('orders'),('order_items'),('messages'),
      ('reports'),('contact_messages'),('seller_plans'),('membership_purchases'),
      ('boost_purchases'),('badge_definitions'),('platform_events'),
      ('seller_payout_accounts'),('seller_balances'),('seller_payout_requests'),
      ('seller_ledger'),('site_carousel_slides'),('admin_notifications'),
      ('site_analytics'),('seller_reviews')
  ),
  expected_columns(table_name, columns) as (
    values
      ('users',array['auth_id','email','phone','full_name','gender','role','user_uid','avatar_url','headline','bio','city','state','business_type','experience_years','profile_completed','active_membership','membership_key','membership_title','membership_badge','membership_banner','membership_expires_at','badge_key','badge_title','banner_key','banner_title','rank_key','rank_title','title_prefix','points','is_founder','founder_number','created_at','updated_at']),
      ('sellers',array['id','user_id','business_name','phone','state','district','city','pincode','address','aadhaar_front','aadhaar_back','shop_photo','status','verification_status','approved_at','banned_at','created_at','updated_at']),
      ('products',array['id','user_id','seller_id','sell_type','condition','title','price','category','brand','model','weight_kg','state','district','city','pincode','description','image_urls','status','is_boosted','views','seller_name','seller_avatar_url','seller_headline','seller_city','seller_state','created_at','updated_at']),
      ('orders',array['id','buyer_id','user_id','amount','shipping_amount','platform_fee','status','payment_id','buyer_name','buyer_phone','address','pincode','shipping_method','coupon_code','coupon_discount','seller_payout_total','platform_commission_total','payout_status','expected_payout_at','created_at','updated_at']),
      ('order_items',array['id','order_id','product_id','quantity','price','seller_user_id','platform_commission','seller_amount','payout_status','created_at']),
      ('messages',array['id','sender_id','receiver_id','product_id','message','is_read','created_at','updated_at']),
      ('reports',array['id','reporter_id','reporter_email','target_type','target_id','product_id','product_title','seller_id','reason','status','created_at','updated_at']),
      ('contact_messages',array['id','user_id','name','phone','topic','message','status','created_at','updated_at']),
      ('seller_plans',array['id','plan_key','name','price','duration_days','listing_limit','boost_days','badge','title','banner','reward_points','active','created_at','updated_at']),
      ('membership_purchases',array['id','user_id','plan_key','plan_name','amount','status','payment_id','starts_at','expires_at','created_at','updated_at']),
      ('boost_purchases',array['id','user_id','product_id','amount','boost_days','status','payment_id','starts_at','expires_at','created_at','updated_at']),
      ('badge_definitions',array['badge_key','name','title','tier','description','rarity','sort_order','active','created_at','updated_at']),
      ('platform_events',array['id','title','description','status','starts_at','ends_at','reward_badge_key','reward_points','created_at','updated_at']),
      ('seller_payout_accounts',array['id','user_id','payout_method','upi_id','account_holder_name','bank_name','account_number','ifsc','created_at','updated_at']),
      ('seller_balances',array['user_id','available_balance','pending_balance','paid_balance','platform_fee_total','last_order_at','created_at','updated_at']),
      ('seller_payout_requests',array['id','user_id','amount','status','payout_method','upi_id','account_holder_name','bank_name','account_number','ifsc','paid_at','created_at','updated_at']),
      ('seller_ledger',array['id','seller_id','order_id','product_id','gross_amount','platform_fee','seller_amount','status','available_on','notes','created_at','updated_at']),
      ('site_carousel_slides',array['id','title','subtitle','image_url','cta_text','cta_route','sort_order','active','created_at','updated_at']),
      ('admin_notifications',array['id','type','subject','body','payload','status','priority','important','admin_email','email_to','email_sent','source','created_at','updated_at']),
      ('site_analytics',array['id','event_type','route','product_id','user_id','session_id','lang','device','referrer','user_agent','metadata','created_at']),
      ('seller_reviews',array['id','seller_id','reviewer_id','rating','comment','status','created_at','updated_at'])
  ),
  column_status as (
    select
      e.table_name,
      count(*) filter (where c.column_name is null) as missing_count,
      string_agg(x.column_name, ', ' order by x.column_name) filter (where c.column_name is null) as missing_columns
    from expected_columns e
    cross join lateral unnest(e.columns) as x(column_name)
    left join information_schema.columns c
      on c.table_schema = 'public'
      and c.table_name = e.table_name
      and c.column_name = x.column_name
    group by e.table_name
  ),
  expected_constraints(name) as (
    values
      ('users_auth_id_fkey'),('sellers_user_id_fkey'),('products_user_id_fkey'),
      ('products_seller_id_fkey'),('orders_buyer_id_fkey'),('order_items_order_id_fkey'),
      ('messages_sender_id_fkey'),('messages_receiver_id_fkey'),('reports_reporter_id_fkey'),
      ('membership_purchases_user_id_fkey'),('seller_payout_accounts_user_id_fkey'),
      ('seller_balances_user_id_fkey'),('seller_payout_requests_user_id_fkey'),
      ('seller_ledger_seller_id_fkey'),('seller_reviews_seller_id_fkey'),
      ('seller_reviews_reviewer_id_fkey')
  ),
  expected_buckets(name) as (
    values ('profile-avatars'),('product-images'),('verification-docs')
  ),
  realtime_tables(name) as (
    values ('users'),('sellers'),('products'),('orders'),('messages'),
      ('membership_purchases'),('seller_ledger'),('seller_balances'),
      ('seller_payout_requests'),('site_carousel_slides'),('seller_reviews'),
      ('admin_notifications')
  )
  select 'table', t.name,
    case when to_regclass('public.' || t.name) is not null then 'OK' else 'MISSING' end
  from expected_tables t
  union all
  select 'columns', c.table_name,
    case when c.missing_count = 0 then 'OK' else 'MISSING: ' || c.missing_columns end
  from column_status c
  union all
  select 'relationship', e.name,
    case when exists (select 1 from pg_constraint pc where pc.conname = e.name) then 'OK' else 'MISSING' end
  from expected_constraints e
  union all
  select 'view', 'public_seller_profiles',
    case when to_regclass('public.public_seller_profiles') is not null then 'OK' else 'MISSING' end
  union all
  select 'bucket', b.name,
    case when exists (select 1 from storage.buckets sb where sb.id = b.name) then 'OK' else 'MISSING' end
  from expected_buckets b
  union all
  select 'realtime', r.name,
    case when exists (
      select 1 from pg_publication_tables p
      where p.pubname = 'supabase_realtime'
        and p.schemaname = 'public'
        and p.tablename = r.name
    ) then 'OK' else 'MISSING' end
  from realtime_tables r;
$$;

revoke all on function public.hp_schema_check() from public;
grant execute on function public.hp_schema_check() to authenticated;

select * from public.hp_schema_check()
order by category, object_name;
