create table if not exists public.site_analytics (
  id bigint generated by default as identity primary key,
  event_type text not null default 'page_view',
  route text not null default 'home',
  product_id text,
  user_id uuid,
  session_id text not null,
  lang text default 'en',
  device text default 'desktop',
  referrer text default 'direct',
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists site_analytics_created_at_idx
  on public.site_analytics (created_at desc);

create index if not exists site_analytics_session_idx
  on public.site_analytics (session_id, created_at desc);

create index if not exists site_analytics_route_idx
  on public.site_analytics (route, created_at desc);

alter table public.site_analytics enable row level security;

drop policy if exists "public can add analytics" on public.site_analytics;
create policy "public can add analytics"
on public.site_analytics
for insert
to anon, authenticated
with check (
  char_length(session_id) between 6 and 120
  and char_length(event_type) between 2 and 40
  and char_length(route) between 1 and 80
);

drop policy if exists "admin can read analytics" on public.site_analytics;
create policy "admin can read analytics"
on public.site_analytics
for select
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.auth_id = auth.uid()
      and (
        lower(coalesce(u.email, '')) = lower('kiratveersinghralhan@gmail.com')
        or u.role = 'admin'
      )
  )
);
